#
#ident	"@(#)Makefile	1.1	97/07/29 SMI"
#
# Copyright (c) 1995 - 1997, by Sun Microsystems, Inc.
# All rights reserved.
#
# lib/libnsl/i386/Makefile
#

include ../Makefile.com

LIBS += $(DYNLIB) $(LINTLIB)

.KEEP_STATE:

all:	$(LIBS)

install:	all $(ROOTLIBS) $(ROOTLINKS) $(ROOTLINT)
