#
# Copyright (c) 1997, by Sun Microsystems, Inc.
# All rights reserved.
#
#ident	"@(#)Makefile	1.1	97/09/03 SMI"
#
# lib/libvolmgt/sparcv9/Makefile

include ../Makefile.com
include ../../Makefile.lib.64

LIBS=	$(DYNLIB) $(LINTLIB)

.KEEP_STATE:

all: $(LIBS) 

install: all $(ROOTLIBS64) $(ROOTLINKS64)
