#
# Copyright (c) 1997, by Sun Microsystems, Inc.
# All rights reserved.
#
#ident	"@(#)Makefile.master.64	1.8	97/10/28 SMI"

# rebind basic build macros to 64-bit versions

CFLAGS=		$(CFLAGS64)
CCFLAGS=	$(CCFLAGS64)
CCOPTFLAG=	$(CCOPTFLAG64)
COMPILE.c=	$(COMPILE64.c)
COMPILE.s=	$(COMPILE64.s)
COMPILE.cc=	$(COMPILE64.cc)
LINK.c=		$(LINK64.c)
LINK.cc=	$(LINK64.cc)
LINT.c=		$(LINT64.c)

#
# Some library path hackery, to allow building of partial workspaces
# and properly set the 64-bit library paths with 'ws'
#
LDLIBS1=	$(ENVLDLIBS1:%=%/$(MACH64))
LDLIBS2=	$(ENVLDLIBS2:%=%/$(MACH64))
LDLIBS3=	$(ENVLDLIBS3:%=%/$(MACH64))
LDLIBS64 = 	$(LDLIBS1) $(LDLIBS2) $(LDLIBS3)
#
# Moved these up to the top level here, so they can be overridden
#
LDLIBS.cmd =	$(LDLIBS64)
LDLIBS.lib =	$(LDLIBS64)

# XX64 all the stuff below this line should go away once the tools are fixed

WYOMING_TOOLS=	$(BUILD_TOOLS)/misc/bin
CC=		$(SPRO_ROOT)/SC5.x/bin/cc
CCC=		$(SPRO_ROOT)/SC5.x/bin/CC
LD=		$(WYOMING_TOOLS)/ld
AR=		$(WYOMING_TOOLS)/ar
LORDER=		$(WYOMING_TOOLS)/lorder
MCS=		$(WYOMING_TOOLS)/mcs
NM=		$(WYOMING_TOOLS)/nm
STRIP=		$(WYOMING_TOOLS)/strip

LDDIR=		$(WYOMING_TOOLS)
BUILD.SO=	$(CC) $(CFLAGS) -Yl,$(LDDIR) -o $@ -G $(DYNFLAGS) $(PICS) -L $(ROOTLIBDIR64) $(LDLIBS)
