#
#pragma ident	"@(#)Makefile.dep	1.2	97/04/24 SMI"
#
nsgmls.o: nsgmls.cxx $(srcdir)/../include/config.h $(srcdir)/../include/Event.h \
 $(srcdir)/../include/Link.h $(srcdir)/../include/Allocator.h $(srcdir)/../include/Location.h \
 $(srcdir)/../include/types.h $(srcdir)/../include/Boolean.h $(srcdir)/../include/Ptr.h \
 $(srcdir)/../include/Resource.h $(srcdir)/../include/Vector.h $(srcdir)/../include/xnew.h \
 $(srcdir)/../include/Owner.h $(srcdir)/../include/StringC.h $(srcdir)/../include/StringOf.h \
 $(srcdir)/../include/rtti.h $(srcdir)/../include/TypeId.h $(srcdir)/../include/Notation.h \
 $(srcdir)/../include/NamedResource.h $(srcdir)/../include/Named.h $(srcdir)/../include/ExternalId.h \
 $(srcdir)/../include/Text.h $(srcdir)/../include/SubstTable.h $(srcdir)/../include/Message.h \
 $(srcdir)/../include/CopyOwner.h $(srcdir)/../include/MessageArg.h \
 $(srcdir)/../include/Attributed.h $(srcdir)/../include/Attribute.h \
 $(srcdir)/../include/StringResource.h $(srcdir)/../include/EntityDecl.h $(srcdir)/../include/Sd.h \
 $(srcdir)/../include/CharsetInfo.h $(srcdir)/../include/UnivCharsetDesc.h \
 $(srcdir)/../include/RangeMap.h $(srcdir)/../include/ISet.h $(srcdir)/../include/Syntax.h \
 $(srcdir)/../include/HashTable.h $(srcdir)/../include/OwnerTable.h \
 $(srcdir)/../include/PointerTable.h $(srcdir)/../include/Hash.h \
 $(srcdir)/../include/HashTableItemBase.h $(srcdir)/../include/XcharMap.h \
 $(srcdir)/../include/constant.h $(srcdir)/../include/EntityCatalog.h \
 $(srcdir)/../include/CharsetDecl.h $(srcdir)/../include/Dtd.h $(srcdir)/../include/NamedTable.h \
 $(srcdir)/../include/NamedResourceTable.h $(srcdir)/../include/ElementType.h \
 $(srcdir)/../include/Mode.h $(srcdir)/../include/ContentToken.h $(srcdir)/../include/NCVector.h \
 $(srcdir)/../include/Entity.h $(srcdir)/../include/Markup.h $(srcdir)/../include/SdText.h \
 $(srcdir)/../include/ShortReferenceMap.h $(srcdir)/../include/Lpd.h \
 $(srcdir)/../include/MessageEventHandler.h $(srcdir)/../include/ErrorCountEventHandler.h \
 SgmlsEventHandler.h $(srcdir)/../include/OutputCharStream.h \
 $(srcdir)/../include/CodingSystem.h StringSet.h $(srcdir)/../include/LinkProcess.h \
 $(srcdir)/../include/IList.h $(srcdir)/../include/IListBase.h RastEventHandler.h \
 $(srcdir)/../include/IQueue.h NsgmlsMessages.h $(srcdir)/../include/ErrnoMessageArg.h \
 $(srcdir)/../include/ParserApp.h $(srcdir)/../include/SgmlParser.h \
 $(srcdir)/../include/EntityManager.h $(srcdir)/../include/ParserOptions.h \
 $(srcdir)/../include/EventsWanted.h $(srcdir)/../include/EntityApp.h \
 $(srcdir)/../include/CmdLineApp.h $(srcdir)/../include/MessageReporter.h \
 $(srcdir)/../include/MessageBuilder.h $(srcdir)/../include/ExtendEntityManager.h \
 $(srcdir)/../include/sptchar.h $(srcdir)/../include/macros.h
SgmlsEventHandler.o: SgmlsEventHandler.cxx $(srcdir)/../include/config.h \
 SgmlsEventHandler.h $(srcdir)/../include/Event.h $(srcdir)/../include/Link.h \
 $(srcdir)/../include/Allocator.h $(srcdir)/../include/Location.h $(srcdir)/../include/types.h \
 $(srcdir)/../include/Boolean.h $(srcdir)/../include/Ptr.h $(srcdir)/../include/Resource.h \
 $(srcdir)/../include/Vector.h $(srcdir)/../include/xnew.h $(srcdir)/../include/Owner.h \
 $(srcdir)/../include/StringC.h $(srcdir)/../include/StringOf.h $(srcdir)/../include/rtti.h \
 $(srcdir)/../include/TypeId.h $(srcdir)/../include/Notation.h $(srcdir)/../include/NamedResource.h \
 $(srcdir)/../include/Named.h $(srcdir)/../include/ExternalId.h $(srcdir)/../include/Text.h \
 $(srcdir)/../include/SubstTable.h $(srcdir)/../include/Message.h $(srcdir)/../include/CopyOwner.h \
 $(srcdir)/../include/MessageArg.h $(srcdir)/../include/Attributed.h \
 $(srcdir)/../include/Attribute.h $(srcdir)/../include/StringResource.h \
 $(srcdir)/../include/EntityDecl.h $(srcdir)/../include/Sd.h $(srcdir)/../include/CharsetInfo.h \
 $(srcdir)/../include/UnivCharsetDesc.h $(srcdir)/../include/RangeMap.h $(srcdir)/../include/ISet.h \
 $(srcdir)/../include/Syntax.h $(srcdir)/../include/HashTable.h $(srcdir)/../include/OwnerTable.h \
 $(srcdir)/../include/PointerTable.h $(srcdir)/../include/Hash.h \
 $(srcdir)/../include/HashTableItemBase.h $(srcdir)/../include/XcharMap.h \
 $(srcdir)/../include/constant.h $(srcdir)/../include/EntityCatalog.h \
 $(srcdir)/../include/CharsetDecl.h $(srcdir)/../include/Dtd.h $(srcdir)/../include/NamedTable.h \
 $(srcdir)/../include/NamedResourceTable.h $(srcdir)/../include/ElementType.h \
 $(srcdir)/../include/Mode.h $(srcdir)/../include/ContentToken.h $(srcdir)/../include/NCVector.h \
 $(srcdir)/../include/Entity.h $(srcdir)/../include/Markup.h $(srcdir)/../include/SdText.h \
 $(srcdir)/../include/ShortReferenceMap.h $(srcdir)/../include/Lpd.h \
 $(srcdir)/../include/OutputCharStream.h $(srcdir)/../include/CodingSystem.h StringSet.h \
 $(srcdir)/../include/LinkProcess.h $(srcdir)/../include/IList.h $(srcdir)/../include/IListBase.h \
 $(srcdir)/../include/ErrorCountEventHandler.h $(srcdir)/../include/SgmlParser.h \
 $(srcdir)/../include/EntityManager.h $(srcdir)/../include/ParserOptions.h \
 $(srcdir)/../include/EventsWanted.h $(srcdir)/../include/ExtendEntityManager.h \
 $(srcdir)/../include/StorageManager.h $(srcdir)/../include/macros.h
RastEventHandler.o: RastEventHandler.cxx $(srcdir)/../include/config.h \
 RastEventHandler.h $(srcdir)/../include/Event.h $(srcdir)/../include/Link.h \
 $(srcdir)/../include/Allocator.h $(srcdir)/../include/Location.h $(srcdir)/../include/types.h \
 $(srcdir)/../include/Boolean.h $(srcdir)/../include/Ptr.h $(srcdir)/../include/Resource.h \
 $(srcdir)/../include/Vector.h $(srcdir)/../include/xnew.h $(srcdir)/../include/Owner.h \
 $(srcdir)/../include/StringC.h $(srcdir)/../include/StringOf.h $(srcdir)/../include/rtti.h \
 $(srcdir)/../include/TypeId.h $(srcdir)/../include/Notation.h $(srcdir)/../include/NamedResource.h \
 $(srcdir)/../include/Named.h $(srcdir)/../include/ExternalId.h $(srcdir)/../include/Text.h \
 $(srcdir)/../include/SubstTable.h $(srcdir)/../include/Message.h $(srcdir)/../include/CopyOwner.h \
 $(srcdir)/../include/MessageArg.h $(srcdir)/../include/Attributed.h \
 $(srcdir)/../include/Attribute.h $(srcdir)/../include/StringResource.h \
 $(srcdir)/../include/EntityDecl.h $(srcdir)/../include/Sd.h $(srcdir)/../include/CharsetInfo.h \
 $(srcdir)/../include/UnivCharsetDesc.h $(srcdir)/../include/RangeMap.h $(srcdir)/../include/ISet.h \
 $(srcdir)/../include/Syntax.h $(srcdir)/../include/HashTable.h $(srcdir)/../include/OwnerTable.h \
 $(srcdir)/../include/PointerTable.h $(srcdir)/../include/Hash.h \
 $(srcdir)/../include/HashTableItemBase.h $(srcdir)/../include/XcharMap.h \
 $(srcdir)/../include/constant.h $(srcdir)/../include/EntityCatalog.h \
 $(srcdir)/../include/CharsetDecl.h $(srcdir)/../include/Dtd.h $(srcdir)/../include/NamedTable.h \
 $(srcdir)/../include/NamedResourceTable.h $(srcdir)/../include/ElementType.h \
 $(srcdir)/../include/Mode.h $(srcdir)/../include/ContentToken.h $(srcdir)/../include/NCVector.h \
 $(srcdir)/../include/Entity.h $(srcdir)/../include/Markup.h $(srcdir)/../include/SdText.h \
 $(srcdir)/../include/ShortReferenceMap.h $(srcdir)/../include/Lpd.h \
 $(srcdir)/../include/OutputCharStream.h $(srcdir)/../include/CodingSystem.h \
 $(srcdir)/../include/LinkProcess.h $(srcdir)/../include/IList.h $(srcdir)/../include/IListBase.h \
 $(srcdir)/../include/IQueue.h $(srcdir)/../include/ErrorCountEventHandler.h \
 $(srcdir)/../include/SgmlParser.h $(srcdir)/../include/EntityManager.h \
 $(srcdir)/../include/ParserOptions.h $(srcdir)/../include/EventsWanted.h \
 RastEventHandlerMessages.h
StringSet.o: StringSet.cxx $(srcdir)/../include/config.h StringSet.h \
 $(srcdir)/../include/StringC.h $(srcdir)/../include/types.h $(srcdir)/../include/StringOf.h \
 $(srcdir)/../include/Boolean.h $(srcdir)/../include/Hash.h $(srcdir)/../include/OwnerTable.h \
 $(srcdir)/../include/PointerTable.h $(srcdir)/../include/Vector.h $(srcdir)/../include/xnew.h
nsgmls_inst.o: nsgmls_inst.cxx $(srcdir)/../include/config.h $(srcdir)/../include/Vector.h \
 $(srcdir)/../include/xnew.h $(srcdir)/../include/Vector.cxx $(srcdir)/../include/PointerTable.h \
 $(srcdir)/../include/Boolean.h $(srcdir)/../include/PointerTable.cxx \
 $(srcdir)/../include/OwnerTable.h $(srcdir)/../include/OwnerTable.cxx $(srcdir)/../include/IQueue.h \
 $(srcdir)/../include/Link.h $(srcdir)/../include/IQueue.cxx $(srcdir)/../include/Owner.h \
 $(srcdir)/../include/Owner.cxx StringSet.h $(srcdir)/../include/StringC.h \
 $(srcdir)/../include/types.h $(srcdir)/../include/StringOf.h $(srcdir)/../include/Hash.h \
 RastEventHandler.h $(srcdir)/../include/Event.h $(srcdir)/../include/Allocator.h \
 $(srcdir)/../include/Location.h $(srcdir)/../include/Ptr.h $(srcdir)/../include/Resource.h \
 $(srcdir)/../include/rtti.h $(srcdir)/../include/TypeId.h $(srcdir)/../include/Notation.h \
 $(srcdir)/../include/NamedResource.h $(srcdir)/../include/Named.h $(srcdir)/../include/ExternalId.h \
 $(srcdir)/../include/Text.h $(srcdir)/../include/SubstTable.h $(srcdir)/../include/Message.h \
 $(srcdir)/../include/CopyOwner.h $(srcdir)/../include/MessageArg.h \
 $(srcdir)/../include/Attributed.h $(srcdir)/../include/Attribute.h \
 $(srcdir)/../include/StringResource.h $(srcdir)/../include/EntityDecl.h $(srcdir)/../include/Sd.h \
 $(srcdir)/../include/CharsetInfo.h $(srcdir)/../include/UnivCharsetDesc.h \
 $(srcdir)/../include/RangeMap.h $(srcdir)/../include/ISet.h $(srcdir)/../include/Syntax.h \
 $(srcdir)/../include/HashTable.h $(srcdir)/../include/HashTableItemBase.h \
 $(srcdir)/../include/XcharMap.h $(srcdir)/../include/constant.h \
 $(srcdir)/../include/EntityCatalog.h $(srcdir)/../include/CharsetDecl.h $(srcdir)/../include/Dtd.h \
 $(srcdir)/../include/NamedTable.h $(srcdir)/../include/NamedResourceTable.h \
 $(srcdir)/../include/ElementType.h $(srcdir)/../include/Mode.h $(srcdir)/../include/ContentToken.h \
 $(srcdir)/../include/NCVector.h $(srcdir)/../include/Entity.h $(srcdir)/../include/Markup.h \
 $(srcdir)/../include/SdText.h $(srcdir)/../include/ShortReferenceMap.h $(srcdir)/../include/Lpd.h \
 $(srcdir)/../include/OutputCharStream.h $(srcdir)/../include/CodingSystem.h \
 $(srcdir)/../include/LinkProcess.h $(srcdir)/../include/IList.h $(srcdir)/../include/IListBase.h \
 $(srcdir)/../include/ErrorCountEventHandler.h
