#
#ident	"@(#)Makefile	1.1	97/05/30 SMI"
#
# Copyright (c) 1997, by Sun Microsystems, Inc.
# All rights reserved.
#
# cmd/dmesg/sparc/Makefile

include ../Makefile.com

install: all $(ROOTUSRSBINPROG32)
