#
#ident	"@(#)Makefile.targ	1.1	97/12/22 SMI"
#
# Copyright (c) 1997 by Sun Microsystems, Inc.
# All rights reserved.
#
# lib/libthread_psr/Makefile.targ
#

include $(SRCDIR)/../Makefile.targ
include $(SRCDIR)/../../Makefile.psm.targ

pics/%.o := ASFLAGS += -K pic
