/* Copyright 1988 - 10/02/96 Sun Microsystems, Inc. All Rights Reserved.
 */

#if !defined(lint) && !defined(NOID)
#ifdef SVR4
#pragma ident  "@(#)manh.c	2.16 96/10/02 Sun Microsystems"
#else
static char sccsid[] = "@(#)manh.c	2.16 96/10/02 Sun Microsystems";
#endif
#endif

/*
** Sun considers its source code as an unpublished, proprietary trade 
** secret, and it is available only under strict license provisions.  
** This copyright notice is placed here only to protect Sun in the event
** the source is deemed a published work.  Disassembly, decompilation, 
** or other means of reducing the object code to human readable form is 
** prohibited by the license agreement under which this code is provided
** to the user or company in possession of this copy.
** 
** RESTRICTED RIGHTS LEGEND: Use, duplication, or disclosure by the 
** Government is subject to restrictions as set forth in subparagraph 
** (c)(1)(ii) of the Rights in Technical Data and Computer Software 
** clause at DFARS 52.227-7013 and in similar clauses in the FAR and 
** NASA FAR Supplement.
*/
/* manh.c
 */

/* $Header: /projects/mibcomp/manh.c,v 1.3 90/11/03 13:08:53 romkey Exp $ */

/* $Log:	manh.c,v $
 * Revision 1.3  90/11/03  13:08:53  romkey
 * got rid of sys/types.h include
 * 
 * Revision 1.2  90/09/17  22:38:17  romkey
 * added copyright, filename and RCS info comments
 * 
 *
 * $Date: 90/11/03 13:08:53 $
 * $Revision: 1.3 $
 * $Author: romkey $
 */

/****************************************************************************
 *     Copyright (c) 1988-1990  Epilogue Technology Corporation
 *     All rights reserved.
 *
 *     This is unpublished proprietary source code of Epilogue Technology
 *     Corporation.
 *
 *     The copyright notice above does not evidence any actual or intended
 *     publication of such source code.
 ****************************************************************************
 */

#include <stdio.h>
#include <sys/types.h>
#include <time.h>

#include "mibcomp.h"

/* This file contains the code which writes a file of stub functions for 
 * a manager; eg: fetch_sysDescr, store_sysName, and also a set of arrays
 * providing the manager with an easy way to access the object id's.
 */

static void _write_ids(), _write_mib(), func_stub();

write_manh(f, source_file)
	char *f;
	char *source_file; {
	FILE *fout;
	time_t now;
	char *s;

	fout = fopen(f, "w");
	if(fout == NULL) {
		perror(f);
		exit(1);
		}

	fprintf(fout, "/*****************************************************************************\n");
	fprintf(fout, " *****************************************************************************\n");
	fprintf(fout, " ****\t\t\tWARNING\n");
	fprintf(fout, " ****\t\n");
	fprintf(fout, " ****\tThis file is automatically generated by the Epilogue Technology\n");
	fprintf(fout, " ****\t MIB compiler.\n");
	fprintf(fout, " ****\t\n");
	fprintf(fout, " ****\tThis file contains functions to allow a manager to fetch and store\n");
	fprintf(fout, " ****\tMIB variables, and their object ID's.\n");
	fprintf(fout, " ****\t\n");
	fprintf(fout, " ****\tDO NOT MODIFY THIS FILE BY HAND\n");
	fprintf(fout, " ****\n");

	time(&now);
	fprintf(fout, " **** Last build date: %s", ctime(&now));
	fprintf(fout, " ****\tfrom file %s\n", source_file);
	fprintf(fout, " *****************************************************************************\n");
	fprintf(fout, " *****************************************************************************\n");

	fprintf(fout, " */\n\n\n");

	fprintf(fout, "#include <asn1.h>\n");
	fprintf(fout, "#include <snmp.h>\n");
	fprintf(fout, "#include <mib.h>\n");
	fprintf(fout, "#include <libfuncs.h>\n\n");

	if(root.kids == NULL) {
		fprintf(stderr, "warning: empty MIB\n");
		return 1;
		}

	/* generate all the object ID's
	 */
	_write_ids(fout, root.kids);
	
	fprintf(fout, "\n");
	}

static void _write_ids(fout, tree)
	FILE *fout;
	struct node *tree; {
	struct node *kid;

	if(tree->flags & FL_LEAF) {
		fprintf(fout, "extern OIDC_T ID_%s[];\n", tree->name);
		fprintf(fout, "extern unsigned int len_%s;\n", tree->name);
		}
	else {
		for(kid = tree->kids; kid; kid = kid->next)
			_write_ids(fout, kid);
		}
	}

