/* Copyright 1988 - 10/02/96 Sun Microsystems, Inc. All Rights Reserved.
 */

#if !defined(lint) && !defined(NOID)
#ifdef SVR4
#pragma ident  "@(#)skel.c	2.16 96/10/02 Sun Microsystems"
#else
static char sccsid[] = "@(#)skel.c	2.16 96/10/02 Sun Microsystems";
#endif
#endif

/*
** Sun considers its source code as an unpublished, proprietary trade 
** secret, and it is available only under strict license provisions.  
** This copyright notice is placed here only to protect Sun in the event
** the source is deemed a published work.  Disassembly, decompilation, 
** or other means of reducing the object code to human readable form is 
** prohibited by the license agreement under which this code is provided
** to the user or company in possession of this copy.
** 
** RESTRICTED RIGHTS LEGEND: Use, duplication, or disclosure by the 
** Government is subject to restrictions as set forth in subparagraph 
** (c)(1)(ii) of the Rights in Technical Data and Computer Software 
** clause at DFARS 52.227-7013 and in similar clauses in the FAR and 
** NASA FAR Supplement.
*/
/* skel.c
 */

/* $Header: /projects/mibcomp/skel.c,v 1.3 90/11/03 13:07:21 romkey Exp $ */

/* $Log:	skel.c,v $
 * Revision 1.3  90/11/03  13:07:21  romkey
 * got rid of sys/types.h include
 * 
 * Revision 1.2  90/09/17  22:38:24  romkey
 * added copyright, filename and RCS info comments
 * 
 *
 * $Date: 90/11/03 13:07:21 $
 * $Revision: 1.3 $
 * $Author: romkey $
 */

/****************************************************************************
 *     Copyright (c) 1988-1990  Epilogue Technology Corporation
 *     All rights reserved.
 *
 *     This is unpublished proprietary source code of Epilogue Technology
 *     Corporation.
 *
 *     The copyright notice above does not evidence any actual or intended
 *     publication of such source code.
 ****************************************************************************
 */


#include <stdio.h>
#include <time.h>
#include <sys/types.h>

#include "mibcomp.h"

static void _write_mib(), func_stub();

write_skel(f, source_file)
	char *f;
	char *source_file; {
	FILE *fout;
	time_t now;
	char *s;

	fout = fopen(f, "w");
	if(fout == NULL) {
		perror(f);
		exit(1);
		}

	fprintf(fout, "/*****************************************************************************\n");
	fprintf(fout, " *****************************************************************************\n");
	fprintf(fout, " ****\t\t\tWARNING\n");
	fprintf(fout, " ****\t\n");
	fprintf(fout, " ****\tThis file is automatically generated by the Epilogue Technology\n");
	fprintf(fout, " ****\t MIB compiler.\n");
	fprintf(fout, " ****\t\n");
	fprintf(fout, " ****\tThis file contains stub function declarations to aid in building\n");	
	fprintf(fout, " ****\tthe agent MIB interface. It defines each MIB get, set, test and next\n");
	fprintf(fout, " ****\tthat must be supplied by the programmer.\n");
	fprintf(fout, " ****\t\n");
	fprintf(fout, " ****\tYOU MAY MODIFY THIS FILE BUT BEWARE ACCIDENTALLY OVERWRITING IT\n");
	fprintf(fout, " ****\tBY REGENERATING IT WITH THE MIB COMPILER.\n");
	fprintf(fout, " ****\n");

	time(&now);
	fprintf(fout, " **** Last build date: %s", ctime(&now));
	fprintf(fout, " ****\tfrom file %s\n", source_file);
	fprintf(fout, " *****************************************************************************\n");
	fprintf(fout, " *****************************************************************************\n");

	fprintf(fout, " */\n\n\n");

	for(s = get_include(); s; s = get_include())
		fprintf(fout, "#include %s\n", s);

	fprintf(fout, "\n");

	/* walk the tree. Start at the root and work down.
	 */
	_write_mib(fout, &root);
        return 1;
	}

static void _write_mib(fout, tree)
	FILE *fout;
	struct node *tree; {
	struct node *kid;

	/* first, emit a node declaration if it's a node, or a leaf
	 * 	declaration if it's got no kids...
	 */
	if(tree->kids || (!(tree->flags & FL_LEAF))) {
		/* if it's got kids, we've got to declare them first, so that
		 * we can build an arc out of them.
		 */
		for(kid = tree->kids; kid; kid = kid->next)
			_write_mib(fout, kid);
		}
	else
		if(tree->flags & FL_LEAF) {	/* only do this if a leaf */
			func_stub(fout, tree);
			}
	}

static void func_stub(fout, n)
	FILE *fout;
	struct node *n; {
	char *func;
	
	accumulate_add("it_exists");
	accumulate_add("std_next");
	accumulate_add("null_get_proc");
	accumulate_add("null_set_proc");

	if((n->flags & FL_READABLE)) {
		func = default_getfunc(n);
		if(accumulate_check(func) == 0) {
			fprintf(fout, "%s %s(lastmatch, compc, compl, cookie)\n",
				n->syntax->c_name, func);
			fprintf(fout, "\tunsigned int lastmatch;\n");
			fprintf(fout, "\tint compc;\n");
			fprintf(fout, "\tunsigned int *compl;\n");
			fprintf(fout, "\tchar *cookie; {\n");
			fprintf(fout, "\t}\n\n");

			accumulate_add(func);
			}
		}

	if((n->flags & FL_WRITEABLE)) {
		func = default_setfunc(n);
		if(accumulate_check(func) == 0) {
			fprintf(fout, "%s %s(lastmatch, compc, compl, cookie)\n",
				n->syntax->c_name, func);
			fprintf(fout, "\tunsigned int lastmatch;\n");
			fprintf(fout, "\tint compc;\n");
			fprintf(fout, "\tunsigned int *compl;\n");
			fprintf(fout, "\tchar *cookie; {\n");
			fprintf(fout, "\t}\n\n");

			accumulate_add(func);
			}
		}

	func = default_testfunc(n);
	if((accumulate_check(func) == 0) && (strcmp(func, "it_exists") != 0)){
		fprintf(fout, "%s %s(lastmatch, compc, compl, cookie)\n",
				n->syntax->c_name, func);
		fprintf(fout, "\tunsigned int lastmatch;\n");
		fprintf(fout, "\tint compc;\n");
		fprintf(fout, "\tunsigned int *compl;\n");
		fprintf(fout, "\tchar *cookie; {\n");
		fprintf(fout, "\t}\n\n");

		accumulate_add(func);
		}

	func = default_nextfunc(n);
	if((accumulate_check(func) == 0) && (strcmp(func, "std_next") != 0)){
		fprintf(fout, "%s %s(lastmatch, compc, compl, cookie)\n",
				n->syntax->c_name, func);
		fprintf(fout, "\tunsigned int lastmatch;\n");
		fprintf(fout, "\tint compc;\n");
		fprintf(fout, "\tunsigned int *compl;\n");
		fprintf(fout, "\tchar *cookie; {\n");
		fprintf(fout, "\t}\n\n");

		accumulate_add(func);
		}
	}
