/* Copyright 08/05/96 Sun Microsystems, Inc. All Rights Reserved.
*/
#pragma ident  "@(#)dmix_msg.h	1.1 96/08/05 Sun Microsystems"

#ifndef _H_DMIX_MSG 
#define _H_DMIX_MSG 
#include <limits.h>
#include <nl_types.h>
#define MF_DMIX "dmix.cat"



/* The following was generated from dmix.msg. */


/* definitions for set DMIX */
#define DMIX 1

#define DMI_BROWSER_LEVEL 1
#define DMTF_TITLE_AIX325 2
#define DMTF_TITLE_AIX41 3
#define DMTF_BADREGISTER_TITLE 4
#define ATTRIBUTE_SET_ERROR 5
#define ATTRIBUTE_SET_ERROR_TITLE 6
#define ATTRIBUTE_TYPE_UNKNOWN 7
#define DMIX_TERM_TITLE 8
#define DMIX_TERM 9
#define DMIX_SIGNAL 10
#define DMIX_DISPLAY_WARNING 11
#define DMIX_DISPLAY 12
#define REGISTER 13
#define UNREGISTER 14
#define BLANK 15
#define EVENT_LOG 16
#define EXIT 17
#define REGISTER_ACCEL 18
#define UNREGISTER_ACCEL 19
#define EVENT_LOG_ACCEL 20
#define EXIT_ACCEL 21
#define INSTALL 22
#define UNINSTALL 23
#define INSTALL_ACCEL 24
#define UNINSTALL_ACCEL 25
#define SLINFO 26
#define PRODINFO 27
#define SLINFO_ACCEL 28
#define PRODINFO_ACCEL 29
#define HELP_INDEX 30
#define HELP_GENERAL 31
#define HELP_USING 32
#define HELP_INDEX_ACCEL 33
#define HELP_GENERAL_ACCEL 34
#define HELP_USING_ACCEL 35
#define OPTIONS 36
#define COMPONENTS 37
#define INFORMATION 38
#define HELP 39
#define OPTIONS_ACCEL 40
#define COMPONENTS_ACCEL 41
#define INFORMATION_ACCEL 42
#define HELP_ACCEL 43
#define PROPERTIES 44
#define REFRESH 45
#define DETAIL_VIEW 46
#define COMPACT_VIEW 47
#define PROPERTIES_ACCEL 48
#define REFRESH_ACCEL 49
#define DETAIL_VIEW_ACCEL 50
#define COMPACT_VIEW_ACCEL 51
#define HELP_GROUP 52
#define HELP_GROUP_ACCEL 53
#define HELP_TITLE 54
#define INSTALL_LABEL 55
#define UNINSTALL_LABEL 56
#define CURRENT_COMPONENTS 57
#define BUTTON_CANCEL 58
#define BUTTON_HELP 59
#define UNINSTALL_ERROR_MESSAGE 60
#define UNINSTALL_ERROR_TITLE 61
#define BUTTON_UNINSTALL 62
#define COMPONENT_INSTALLED 63
#define COMPONENT_NOT_INSTALLED 64
#define DMI_INSTALL_FAIL 65
#define DMI_INSTALL_FINI 66
#define DMTF_STATUS_SL_DEAD 67
#define DMTF_STATUS_SL_DEAD2 68
#define INSTALL_IN_PROGRESS 69
#define INSTALL_MIF 70
#define UNINSTALL_IN_PROGRESS 71
#define UNINSTALL_MIF 72
#define SPECLEVEL 73
#define SLDESC 74
#define PRODINFOTITLE 75
#define SLINFOTITLE 76
#define INSTALL_ERROR_TITLE 77
#define LABEL_ID 78
#define LABEL_NAME 79
#define CLASSLIST 80
#define DEFAULT_DESCRIPTION 81
#define DESCRIPTION 82
#define BUTTON_CLOSE 83
#define COMPONENT_INFORMATION 84
#define LABEL_VALUE 85
#define LABEL_TYPE 86
#define LABEL_ACCESS_TYPE 87
#define LABEL_MAX_SIZE 88
#define ENUM_LIST 89
#define BUTTON_APPLY 90
#define BUTTON_RESET 91
#define BUTTON_GETCURRENT 92
#define ATTRIBUTE_INFORMATION 93
#define EVENT_LOG_LABEL 94
#define BUTTON_CLEAR 95
#define EVENT_VIEWER 96
#define LABEL_COMPONENT 97
#define LABEL_CLASS 98
#define BAD_CLASS_STRING_OFFSET 99
#define LABEL_GROUP 100
#define LABEL_NO_KEYS 101
#define LABEL_NO_ATTRIBUTES 102
#define LABEL_ATTRIBUTE_ID 103
#define BAD_ATTRIBUTE_OFFSET 104
#define BAD_ROW_OFFSET 105
#define DMTF_READONLY 106
#define DMTF_READWRITE 107
#define DMTF_WRITEONLY 108
#define DMTF_READONLYC 109
#define DMTF_READWRITEC 110
#define DMTF_WRITEONLYC 111
#define DMTF_UNKNOWN 112
#define DMTF_NOVALUE 113
#define DMTF_COUNTER32 114
#define DMTF_INT64 115
#define DMTF_DATE 116
#define DMTF_BADVALUE 117
#define DMTF_COUNTER64 118
#define DMTF_DISPLAYSTRING 119
#define DMTF_GAUGE 120
#define DMTF_INTEGER 121
#define DMTF_OCTETSTRING 122
#define DMTF_NOCLASS 123
#define DMTF_BADREGISTER 124
#define DMTF_BAD_DEREGISTER 125
#define DMTF_UNSUPPORTED 126
#define ATTR_VALUE_UNKNOWN 127
#define ATTR_VALUE_UNSUPPORTED 128
#define GROUP_PRAGMA 129

/* definitions for set DMIERROR */
#define DMIERROR 2

#endif 
