#
#ident	"@(#)Makefile	1.2	98/01/20 SMI"
#
# Copyright (c) 1993 by Sun Microsystems, Inc.
#

include ../Makefile.com

DATAFILES += i.renamenew i.renameold i.initd i.preserve

.KEEP_STATE:

all: $(FILES)
install: all pkg

include ../Makefile.targ
