#
# Copyright (c) 1997, by Sun Microsystems, Inc.
# All rights reserved.
#
#ident	"@(#)Makefile 1.2	97/10/09 SMI"
#
# lib/libplot/t300s/i386/Makefile

include ../Makefile.com

all: $(LIBS) $(LINTLIB)

.KEEP_STATE:

install: all $(ROOTLIBS) $(ROOTLINKS) $(ROOTLINT)
