#
# Copyright (c) 1997, by Sun Microsystems, Inc.
# All rights reserved.
#
#ident	"@(#)Makefile	1.3	97/08/28 SMI"
#
# lib/libkvm/i386/Makefile

include ../Makefile.com

DYNFLAGS += $(DYNFLAGS32)

.KEEP_STATE:

all: $(LIBS)

install: all $(ROOTLIBS) $(ROOTLINKS) $(ROOTLINT)
