#
#ident	"@(#)Makefile	1.3	97/08/28 SMI"
#
# Copyright (c) 1997 by Sun Microsystems, Inc.
#
# lib/libmapmalloc/i386/Makefile
#

include ../Makefile.com

.KEEP_STATE:

all: $(LIBS)

install: all $(ROOTLIBS) $(ROOTLINKS) $(ROOTLINT)
