#
#ident	"@(#)Makefile	1.3	97/09/11 SMI"
#
# Copyright (c) 1997 by Sun Microsystems, Inc.
#
# lib/libeti/panel/sparc/Makefile
#

include ../Makefile.com
include ../../../Makefile.lib.64

DYNFLAGS += $(DYNFLAGS64)

.KEEP_STATE:

install: all $(ROOTLIBS64) $(ROOTLINKS64)
