#
# Copyright (c) 1997, by Sun Microsystems, Inc.
# All rights reserved.
#
#ident	"@(#)Makefile	1.2	97/08/27 SMI"
#
# lib/nametoaddr/straddr/sparcv9/Makefile

include ../Makefile.com
include ../../../Makefile.lib.64

LIBS=	$(DYNLIB)

.KEEP_STATE:

install: all $(ROOTLIBS64) $(ROOTLINKS64)
