#
# Copyright (c) 1997-1998, by Sun Microsystems, Inc.
# All rights reserved.
#
#ident	"@(#)Makefile	1.2	98/01/21 SMI"
#
# lib/libcfgadm/sparcv9/Makefile

include ../Makefile.com
include ../../Makefile.lib.64

LIBS=	$(DYNLIB) $(LINTLIB)

.KEEP_STATE:

install: all $(ROOTLIBS64) $(ROOTLINKS64)
