#
#ident	"@(#)Makefile	1.2	97/11/09 SMI"
#
# Copyright (c) 1993 by Sun Microsystems, Inc.
#

include ../Makefile.com

DATAFILES += i.preserve

.KEEP_STATE:

all: $(FILES)
install: all pkg

include ../Makefile.targ
