#!/sbin/sh
#
# Copyright (c) 1994-1997 by Sun Microsystems, Inc.
# All rights reserved.
#
#ident	"@(#)mkdtab	1.10	97/12/08 SMI"

#
# Update device.tab and dgroup.tab files to reflect configuration.
# Script runs once at installation time and then removes itself.
#

if [ -x /usr/sadm/sysadm/bin/mkdtab ]; then
	/usr/sadm/sysadm/bin/mkdtab
	/usr/bin/rm -f /etc/rc2.d/S82mkdtab
fi
