#!/sbin/sh
#
# Copyright (c) 1997 by Sun Microsystems, Inc.
# All rights reserved.
#
#ident	"@(#)MOUNTFSYS	1.13	97/12/08 SMI"

if [ -z "$_INIT_PREV_LEVEL" ]; then
	set -- `/usr/bin/who -r`
	_INIT_PREV_LEVEL="$9"
fi

if [ $_INIT_PREV_LEVEL = S ]; then
	# Mount all local filesystems.  After this, /tmp will be appropriately
	# mounted so fire off a ps in the background to build ps_data.

	cd /; /sbin/mountall -l
	/usr/bin/ps -o pid >/dev/null 2>&1 &
fi

# Make sure /usr subtree is present by testing for /usr/sbin

if [ ! -d /usr/sbin ]; then
	echo "WARNING: /usr subtree is missing: changing to single user mode"
	/sbin/init S
fi

# If there are mounted filesystems with quotas enabled, check them

if /usr/bin/cut -f 4 /etc/mnttab | \
  /usr/bin/egrep '^quota|,quota' >/dev/null 2>&1; then

	echo 'Checking UFS quotas: \c'
	/usr/sbin/quotacheck -a -p
	echo 'done.'
	/usr/sbin/quotaon -a
fi
