#!/sbin/sh
#
# Copyright (c) 1997-1998 by Sun Microsystems, Inc.
# All rights reserved.
#
#ident	"@(#)nfs.client	1.11	98/02/22 SMI"

[ ! -d /usr/bin ] && exit

#
# Start/stop processes required for client NFS
#

case "$1" in
'start')
	if [ -x /usr/lib/nfs/statd -a -x /usr/lib/nfs/lockd ]; then
		/usr/bin/pgrep -x -u 0 statd >/dev/null 2>&1 || \
		    /usr/lib/nfs/statd >/dev/console 2>&1 &

		/usr/bin/pgrep -x -u 0 lockd >/dev/null 2>&1 || \
		    /usr/lib/nfs/lockd >/dev/console 2>&1 &
	fi

	# Obtain kerberos ticket before attempting kerberos NFS mounts

	if [ -x /usr/bin/ksrvtgt ] && \
	    /usr/bin/egrep '^[^#].*kerberos' /etc/vfstab >/dev/null 2>&1; then

		[ -z "$_INIT_UTS_NODENAME" ] && \
		    _INIT_UTS_NODENAME=`/usr/bin/uname -n`

		warn1="cannot get kerberos ticket for root.$_INIT_UTS_NODENAME"
		warn2=`/usr/bin/ksrvtgt root $_INIT_UTS_NODENAME 2>&1`

		if [ $? -ne 0 ]; then
		    echo "Warning: $warn1" >& 2
		    echo "  ksrvtgt error: $warn2" >& 2
		fi
	fi

	/sbin/mountall -F nfs
	/sbin/mountall -F cachefs
	/sbin/swapadd
	;;

'stop')
	/usr/bin/pkill -x -u 0 '(lockd|statd)'
	/sbin/umountall -F cachefs
	/sbin/umountall -F nfs
	;;

*)
	echo "Usage: $0 { start | stop }"
	exit 1
	;;
esac
exit 0
