#!/sbin/sh
#
# Copyright (c) 1994-1997 by Sun Microsystems, Inc.
# All rights reserved.
#
#ident	"@(#)pcmcia	1.5	97/12/08 SMI"

case "$1" in
'start')
	if [ -c /dev/pem -a -f /usr/lib/pcmciad ] ; then
		/usr/lib/pcmciad 1>/dev/console 2>&1 && \
			echo 'starting PCMCIA user daemon.'
	fi
	;;

'stop')
	/usr/bin/pkill -x -u 0 pcmciad
	;;

*)
	echo "Usage: $0 { start | stop }"
	exit 1
	;;
esac
exit 0
