#!/sbin/sh
#
# Copyright (c) 1991, 1997 by Sun Microsystems, Inc.
# All rights reserved.
#
#ident	"@(#)syslog	1.8	97/12/08 SMI"

case "$1" in
'start')
	if [ -f /etc/syslog.conf -a -f /usr/sbin/syslogd ]; then
		echo 'syslog service starting.'
		[ ! -f /var/adm/messages ] && \
		    /usr/bin/cp /dev/null /var/adm/messages
		/usr/sbin/syslogd >/dev/console 2>&1 &
	fi
	;;

'stop')
	if [ -f /etc/syslog.pid ]; then
		syspid=`/usr/bin/cat /etc/syslog.pid`
		[ "$syspid" -gt 0 ] && kill -15 $syspid
	fi
	;;

*)
	echo "Usage: $0 { start | stop }"
	exit 1
	;;
esac
