#!/sbin/sh
#
# Copyright (c) 1997 by Sun Microsystems, Inc.
# All rights reserved.
#
#ident	"@(#)volmgt	1.5	97/12/08 SMI"

case "$1" in
'start')
	if [ -f /etc/vold.conf -a -f /usr/sbin/vold ]; then
		echo 'volume management starting.'
		/usr/sbin/vold >/dev/console 2>&1 &
	fi
	;;

'stop')
	/usr/bin/pkill -x -u 0 vold
	;;

*)
	echo "Usage: $0 { start | stop }"
	exit 1
	;;

esac
exit 0
