#
# Copyright (c) 1997, by Sun Microsystems, Inc.
# All rights reserved.
#
#ident	"@(#)Makefile	1.1	97/05/15 SMI"
#
# lib/liblm/sparcv9/Makefile

include ../Makefile.com
include ../../Makefile.lib.64

.KEEP_STATE:

install: all $(ROOTLIBS64) $(ROOTLINKS64)
