#!/sbin/sh
#
# Copyright (c) 1996-1997 by Sun Microsystems, Inc.
# All rights reserved.
#
#ident	"@(#)dhcp	1.16	97/12/08 SMI"

# Make sure that /usr is mounted
[ ! -d /usr/bin ] && exit 1

DHCPDOPTIONS=""

case "$1" in
'start')
	if [ -x /usr/lib/inet/in.dhcpd ]; then

		if [ -f /etc/default/dhcp -o -d /tftpboot ]; then
			/usr/lib/inet/in.dhcpd $DHCPDOPTIONS >/dev/console 2>&1

		elif [ -n "$DHCPDOPTIONS" ] && \
		    echo "$DHCPDOPTIONS" | grep -s '\-r' >/dev/null; then

			/usr/lib/inet/in.dhcpd $DHCPDOPTIONS >/dev/console 2>&1
		fi
	fi
	;;

'stop')
	/usr/bin/pkill -x -u 0 in.dhcpd
	;;

*)
	echo "Usage: $0 { start | stop }"
	exit 1
	;;
esac
exit 0
