#
# Copyright (c) 1997, by Sun Microsystems, Inc.
# All rights reserved.
#
#ident  "@(#)Makefile   1.1     97/08/22 SMI"
#
# lib/fn/libxfn/sparc/Makefile
#

include ../Makefile.com

MAPFILES=      ../common/mapfile-vers  ../$(MACH)/mapfile-vers

.KEEP_STATE:

install debug tcov: $(ROOTLIBDIR) $(ROOTLIBS) \
                $(ROOTLINKSCCC)
