#
#ident	"@(#)Makefile	1.2	96/11/14 SMI"
#
# Copyright (c) 1996, by Sun Microsystems, Inc.
# All rights reserved.

include ../Makefile.com

.KEEP_STATE:

DATAFILES += depend

all: $(FILES) $(MACHDATAFILES)
install: all pkg

include ../Makefile.targ
