#
# Copyright (c) 1997, by Sun Microsystems, Inc.
# All rights reserved.
#
#ident	"@(#)Makefile 1.1	97/09/25 SMI"
#
# lib/libplot/plot/i386/Makefile

include ../Makefile.com

all: $(LIBS)

.KEEP_STATE:

install: all $(ROOTLIBS) $(ROOTLINKS) $(ROOTLINT)
