## THIS FILE WAS GENERATED BY MIB2SCHEMA
## For attributes containing printable ASCII
## characters, you may add a format string
## specification in the attribute characteristics
## line
## As described in RFC 1157, some agents cannot
## accept messages whose length exceeds 484 octets
## For those groups whose var-bind list has many
## entries, you may split them up into different
## var-bind lists
proxy DMTFDEVELOPERS-DIRECTINTERFACEVERSION-MIB
description "DMTFDEVELOPERS-DIRECTINTERFACEVERSION-MIB agent"
serial 2
rpcid 100122
(

## Enumerated Type Definitions


## Group and Table Declarations

	table	tComponentid
	description "This group defines attributes common to all components.Th"
	characteristics "-K ONE"
	(
		readonly string[128]	a1Manufacturer
		description 	"The name of the manufacturer that produces this component."
		characteristics "-N a1Manufacturer -O 1.3.6.1.4.1.42.2000.2.1.1.1.1.1 -T STRING -A RO -X equal -F 0"

		readonly string[128]	a1Product
		description 	"The name of the component."
		characteristics "-N a1Product -O 1.3.6.1.4.1.42.2000.2.1.1.1.1.2 -T STRING -A RO -X equal -F 0"

		readonly string[128]	a1Version
		description 	"The version for the component."
		characteristics "-N a1Version -O 1.3.6.1.4.1.42.2000.2.1.1.1.1.3 -T STRING -A RO -X equal -F 0"

		readonly string[128]	a1SerialNumber
		description 	"The serial number for this instance of this component."
		characteristics "-N a1SerialNumber -O 1.3.6.1.4.1.42.2000.2.1.1.1.1.4 -T STRING -A RO -X equal -F 0"

		readonly octet[128]	a1Installation
		description 	"The time and date of the last install of this component."
		characteristics "-N a1Installation -O 1.3.6.1.4.1.42.2000.2.1.1.1.1.5 -T STRING -A RO -X equal -F 0"

		readonly int	a1Verify
		description 	"Verification."
		characteristics "-N a1Verify -O 1.3.6.1.4.1.42.2000.2.1.1.1.1.6 -T INTEGER -A RO -X equal -F 0"

		readonly int	a1Componentid
		description 	"The trap info. of the new installed component."
		characteristics "-N a1Componentid -O 1.3.6.1.4.1.42.2000.2.1.1.1.1.7 -T INTEGER -A RO -X equal -F 0"

		readonly string[128]	a1Componentname
		description 	"The trap info for Component name."
		characteristics "-N a1Componentname -O 1.3.6.1.4.1.42.2000.2.1.1.1.1.8 -T STRING -A RO -X equal -F 0"

		readonly string[128]	a1Componentdesc
		description 	"The trap info for Component Desc."
		characteristics "-N a1Componentdesc -O 1.3.6.1.4.1.42.2000.2.1.1.1.1.9 -T STRING -A RO -X equal -F 0"

		readonly int	a1Groupid
		description 	"The trap info for Group Id."
		characteristics "-N a1Groupid -O 1.3.6.1.4.1.42.2000.2.1.1.1.1.10 -T INTEGER -A RO -X equal -F 0"

		readonly string[128]	a1Groupname
		description 	"The trap info for Group Name."
		characteristics "-N a1Groupname -O 1.3.6.1.4.1.42.2000.2.1.1.1.1.11 -T STRING -A RO -X equal -F 0"

		readonly string[128]	a1Languagename
		description 	"The trap info for Language Name."
		characteristics "-N a1Languagename -O 1.3.6.1.4.1.42.2000.2.1.1.1.1.12 -T STRING -A RO -X equal -F 0"

	)

	table	tNames
	description "DMTF Developers names. Direct Interface Version"
	characteristics "-K ONE"
	(
		readonly int	a2Index
		description 	"Index into names table."
		characteristics "-N a2Index -O 1.3.6.1.4.1.42.2000.2.1.1.2.1.10 -T INTEGER -A RO -X equal -F 0"

		readwrite string[128]	a2Name
		description 	"Name of the developer."
		characteristics "-N a2Name -O 1.3.6.1.4.1.42.2000.2.1.1.2.1.20 -T STRING -A RW -X equal -F 0"

		readwrite string[128]	a2Company
		description 	"Corporation that this developer works for."
		characteristics "-N a2Company -O 1.3.6.1.4.1.42.2000.2.1.1.2.1.30 -T STRING -A RW -X equal -F 0"

		readwrite string[128]	a2OperatingSystemEnv
		description 	"The Operating system or Environment that this developer built
code for."
		characteristics "-N a2OperatingSystemEnv -O 1.3.6.1.4.1.42.2000.2.1.1.2.1.40 -T STRING -A RW -X equal -F 0"

	)

	table	tSoftwareTable
	description ""
	characteristics "-K ???"
	(
		readonly string[128]	a42ProductName
		description 	"The name of the product"
		characteristics "-N a42ProductName -O 1.3.6.1.4.1.42.2000.2.1.1.42.1.1 -T STRING -A RO -X equal -F 0"

		readonly string[128]	a42ProductVersion
		description 	"The product's version number"
		characteristics "-N a42ProductVersion -O 1.3.6.1.4.1.42.2000.2.1.1.42.1.2 -T STRING -A RO -X equal -F 0"

	)

agenterrors (
	1	"cannot dispatch request"
	2	"select(2) failed"
	3	"sendto(2) failed"
	4	"recvfrom(2) failed"
	5	"no response from system"
	6	"response too big"
	7	"missing attribute"
	8	"bad attribute type"
	9	"cannot get sysUpTime"
	10	"sysUpTime type bad"
	11	"unknown SNMP error"
	12	"bad variable value"
	13	"variable is read only"
	14	"general error"
	15	"cannot make request PDU"
	16	"cannot make request varbind list"
	17	"cannot parse response PDU"
	18	"request ID - response ID mismatch"
	19	"string contains non-displayable characters"
	20	"cannot open schema file"
	21	"cannot parse schema file"
	22	"cannot open host file"
	23	"cannot parse host file"
	24	"attribute unavailable for set operations"
             )
)


## End of Agent Definitions
