#!/bin/sh
#
#ident	"@(#)preremove	1.1	97/11/09 SMI"
#
# Copyright (c) 1992 by Sun Microsystems, Inc.
#
#

#	remove the libcrypt.* symlinks
#

rm -f $BASEDIR/usr/lib/libcrypt.so
rm -f $BASEDIR/usr/lib/libcrypt.so.1

exit 0
