#
# Copyright (c) 1997-1998, by Sun Microsystems, Inc.
# All rights reserved.
#
#ident	"@(#)Makefile	1.2	98/01/21 SMI"
#
# lib/libcfgadm/i386/Makefile

include ../Makefile.com

.KEEP_STATE:

install: all $(ROOTLIBS) $(ROOTLINKS) $(ROOTLINT)
