#
# Copyright (c) 1997, by Sun Microsystems, Inc.
# All rights reserved.
#
#ident	"@(#)Makefile 1.1	97/09/25 SMI"
#
# lib/libplot/plot/sparcv9/Makefile

include ../Makefile.com
include ../../../Makefile.lib.64

LIBS= $(DYNLIB) $(LINTLIB)

all: $(LIBS)

.KEEP_STATE:

install: all $(ROOTLIBS64) $(ROOTLINKS64)
