/* Copyright 09/11/96 Sun Microsystems, Inc. All Rights Reserved.
 */

/*
 * Please do not edit this file.
 * It was generated using rpcgen.
 */

#include "ci_callback.h"

bool_t
xdr_CiGetAttributeIN(register XDR *xdrs, CiGetAttributeIN *objp)
{

	register long *buf;

	if (!xdr_DmiId_t(xdrs, &objp->componentId))
		return (FALSE);
	if (!xdr_DmiId_t(xdrs, &objp->groupId))
		return (FALSE);
	if (!xdr_DmiId_t(xdrs, &objp->attributeId))
		return (FALSE);
	if (!xdr_pointer(xdrs, (char **)&objp->language, sizeof (DmiString_t), (xdrproc_t) xdr_DmiString_t))
		return (FALSE);
	if (!xdr_pointer(xdrs, (char **)&objp->keyList, sizeof (DmiAttributeValues_t), (xdrproc_t) xdr_DmiAttributeValues_t))
		return (FALSE);
	return (TRUE);
}

bool_t
xdr_CiGetAttributeOUT(register XDR *xdrs, CiGetAttributeOUT *objp)
{

	register long *buf;

	if (!xdr_DmiErrorStatus_t(xdrs, &objp->error_status))
		return (FALSE);
	if (!xdr_pointer(xdrs, (char **)&objp->data, sizeof (DmiAttributeData_t), (xdrproc_t) xdr_DmiAttributeData_t))
		return (FALSE);
	return (TRUE);
}

bool_t
xdr_CiGetNextAttributeIN(register XDR *xdrs, CiGetNextAttributeIN *objp)
{

	register long *buf;

	if (!xdr_DmiId_t(xdrs, &objp->componentId))
		return (FALSE);
	if (!xdr_DmiId_t(xdrs, &objp->groupId))
		return (FALSE);
	if (!xdr_DmiId_t(xdrs, &objp->attributeId))
		return (FALSE);
	if (!xdr_pointer(xdrs, (char **)&objp->language, sizeof (DmiString_t), (xdrproc_t) xdr_DmiString_t))
		return (FALSE);
	if (!xdr_pointer(xdrs, (char **)&objp->keyList, sizeof (DmiAttributeValues_t), (xdrproc_t) xdr_DmiAttributeValues_t))
		return (FALSE);
	return (TRUE);
}

bool_t
xdr_CiGetNextAttributeOUT(register XDR *xdrs, CiGetNextAttributeOUT *objp)
{

	register long *buf;

	if (!xdr_DmiErrorStatus_t(xdrs, &objp->error_status))
		return (FALSE);
	if (!xdr_pointer(xdrs, (char **)&objp->data, sizeof (DmiAttributeData_t), (xdrproc_t) xdr_DmiAttributeData_t))
		return (FALSE);
	return (TRUE);
}

bool_t
xdr_CiSetAttributeIN(register XDR *xdrs, CiSetAttributeIN *objp)
{

	register long *buf;

	if (!xdr_DmiId_t(xdrs, &objp->componentId))
		return (FALSE);
	if (!xdr_DmiId_t(xdrs, &objp->groupId))
		return (FALSE);
	if (!xdr_DmiId_t(xdrs, &objp->attributeId))
		return (FALSE);
	if (!xdr_pointer(xdrs, (char **)&objp->language, sizeof (DmiString_t), (xdrproc_t) xdr_DmiString_t))
		return (FALSE);
	if (!xdr_pointer(xdrs, (char **)&objp->keyList, sizeof (DmiAttributeValues_t), (xdrproc_t) xdr_DmiAttributeValues_t))
		return (FALSE);
	if (!xdr_pointer(xdrs, (char **)&objp->data, sizeof (DmiAttributeData_t), (xdrproc_t) xdr_DmiAttributeData_t))
		return (FALSE);
	return (TRUE);
}

bool_t
xdr_CiReserveAttributeIN(register XDR *xdrs, CiReserveAttributeIN *objp)
{

	register long *buf;

	if (!xdr_DmiId_t(xdrs, &objp->componentId))
		return (FALSE);
	if (!xdr_DmiId_t(xdrs, &objp->groupId))
		return (FALSE);
	if (!xdr_DmiId_t(xdrs, &objp->attributeId))
		return (FALSE);
	if (!xdr_pointer(xdrs, (char **)&objp->keyList, sizeof (DmiAttributeValues_t), (xdrproc_t) xdr_DmiAttributeValues_t))
		return (FALSE);
	if (!xdr_pointer(xdrs, (char **)&objp->data, sizeof (DmiAttributeData_t), (xdrproc_t) xdr_DmiAttributeData_t))
		return (FALSE);
	return (TRUE);
}

bool_t
xdr_CiReleaseAttributeIN(register XDR *xdrs, CiReleaseAttributeIN *objp)
{

	register long *buf;

	if (!xdr_DmiId_t(xdrs, &objp->componentId))
		return (FALSE);
	if (!xdr_DmiId_t(xdrs, &objp->groupId))
		return (FALSE);
	if (!xdr_DmiId_t(xdrs, &objp->attributeId))
		return (FALSE);
	if (!xdr_pointer(xdrs, (char **)&objp->keyList, sizeof (DmiAttributeValues_t), (xdrproc_t) xdr_DmiAttributeValues_t))
		return (FALSE);
	if (!xdr_pointer(xdrs, (char **)&objp->data, sizeof (DmiAttributeData_t), (xdrproc_t) xdr_DmiAttributeData_t))
		return (FALSE);
	return (TRUE);
}

bool_t
xdr_CiAddRowIN(register XDR *xdrs, CiAddRowIN *objp)
{

	register long *buf;

	if (!xdr_pointer(xdrs, (char **)&objp->rowData, sizeof (DmiRowData_t), (xdrproc_t) xdr_DmiRowData_t))
		return (FALSE);
	return (TRUE);
}

bool_t
xdr_CiDeleteRowIN(register XDR *xdrs, CiDeleteRowIN *objp)
{

	register long *buf;

	if (!xdr_pointer(xdrs, (char **)&objp->rowData, sizeof (DmiRowData_t), (xdrproc_t) xdr_DmiRowData_t))
		return (FALSE);
	return (TRUE);
}
