/* Copyright 09/11/96 Sun Microsystems, Inc. All Rights Reserved.
 */

#pragma ident  "@(#)ci_callback_clnt.c	1.2 96/09/11 Sun Microsystems"

/*
 * Please do not edit this file.
 * It was generated using rpcgen.
 */

#include <memory.h> /* for memset */
#include "ci_callback.h"

/* Default timeout can be changed using clnt_control() */
static struct timeval TIMEOUT = { 25, 0 };

CiGetAttributeOUT *
_cigetattribute_0x1(CiGetAttributeIN *argp, CLIENT *clnt)
{
	static CiGetAttributeOUT clnt_res;

	memset((char *)&clnt_res, 0, sizeof (clnt_res));
	if (clnt_call(clnt, _CiGetAttribute,
		(xdrproc_t) xdr_CiGetAttributeIN, (caddr_t) argp,
		(xdrproc_t) xdr_CiGetAttributeOUT, (caddr_t) &clnt_res,
		TIMEOUT) != RPC_SUCCESS) {
		return (NULL);
	}
	return (&clnt_res);
}

CiGetNextAttributeOUT *
_cigetnextattribute_0x1(CiGetNextAttributeIN *argp, CLIENT *clnt)
{
	static CiGetNextAttributeOUT clnt_res;

	memset((char *)&clnt_res, 0, sizeof (clnt_res));
	if (clnt_call(clnt, _CiGetNextAttribute,
		(xdrproc_t) xdr_CiGetNextAttributeIN, (caddr_t) argp,
		(xdrproc_t) xdr_CiGetNextAttributeOUT, (caddr_t) &clnt_res,
		TIMEOUT) != RPC_SUCCESS) {
		return (NULL);
	}
	return (&clnt_res);
}

DmiErrorStatus_t *
_cisetattribute_0x1(CiSetAttributeIN *argp, CLIENT *clnt)
{
	static DmiErrorStatus_t clnt_res;

	memset((char *)&clnt_res, 0, sizeof (clnt_res));
	if (clnt_call(clnt, _CiSetAttribute,
		(xdrproc_t) xdr_CiSetAttributeIN, (caddr_t) argp,
		(xdrproc_t) xdr_DmiErrorStatus_t, (caddr_t) &clnt_res,
		TIMEOUT) != RPC_SUCCESS) {
		return (NULL);
	}
	return (&clnt_res);
}

DmiErrorStatus_t *
_cireserveattribute_0x1(CiReserveAttributeIN *argp, CLIENT *clnt)
{
	static DmiErrorStatus_t clnt_res;

	memset((char *)&clnt_res, 0, sizeof (clnt_res));
	if (clnt_call(clnt, _CiReserveAttribute,
		(xdrproc_t) xdr_CiReserveAttributeIN, (caddr_t) argp,
		(xdrproc_t) xdr_DmiErrorStatus_t, (caddr_t) &clnt_res,
		TIMEOUT) != RPC_SUCCESS) {
		return (NULL);
	}
	return (&clnt_res);
}

DmiErrorStatus_t *
_cireleaseattribute_0x1(CiReleaseAttributeIN *argp, CLIENT *clnt)
{
	static DmiErrorStatus_t clnt_res;

	memset((char *)&clnt_res, 0, sizeof (clnt_res));
	if (clnt_call(clnt, _CiReleaseAttribute,
		(xdrproc_t) xdr_CiReleaseAttributeIN, (caddr_t) argp,
		(xdrproc_t) xdr_DmiErrorStatus_t, (caddr_t) &clnt_res,
		TIMEOUT) != RPC_SUCCESS) {
		return (NULL);
	}
	return (&clnt_res);
}

DmiErrorStatus_t *
_ciaddrow_0x1(CiAddRowIN *argp, CLIENT *clnt)
{
	static DmiErrorStatus_t clnt_res;

	memset((char *)&clnt_res, 0, sizeof (clnt_res));
	if (clnt_call(clnt, _CiAddRow,
		(xdrproc_t) xdr_CiAddRowIN, (caddr_t) argp,
		(xdrproc_t) xdr_DmiErrorStatus_t, (caddr_t) &clnt_res,
		TIMEOUT) != RPC_SUCCESS) {
		return (NULL);
	}
	return (&clnt_res);
}

DmiErrorStatus_t *
_cideleterow_0x1(CiDeleteRowIN *argp, CLIENT *clnt)
{
	static DmiErrorStatus_t clnt_res;

	memset((char *)&clnt_res, 0, sizeof (clnt_res));
	if (clnt_call(clnt, _CiDeleteRow,
		(xdrproc_t) xdr_CiDeleteRowIN, (caddr_t) argp,
		(xdrproc_t) xdr_DmiErrorStatus_t, (caddr_t) &clnt_res,
		TIMEOUT) != RPC_SUCCESS) {
		return (NULL);
	}
	return (&clnt_res);
}
