/* Copyright 09/11/96 Sun Microsystems, Inc. All Rights Reserved.
 */

/*
 * Please do not edit this file.
 * It was generated using rpcgen.
 */

#include <memory.h> /* for memset */
#include "server.h"

/* Default timeout can be changed using clnt_control() */
static struct timeval TIMEOUT = { 50, 0 };

DmiRegisterOUT *
_dmiregister_0x1(DmiRegisterIN *argp, CLIENT *clnt)
{
	static DmiRegisterOUT clnt_res;

	memset((char *)&clnt_res, 0, sizeof (clnt_res));
	if (clnt_call(clnt, _DmiRegister,
		(xdrproc_t) xdr_DmiRegisterIN, (caddr_t) argp,
		(xdrproc_t) xdr_DmiRegisterOUT, (caddr_t) &clnt_res,
		TIMEOUT) != RPC_SUCCESS) {
		return (NULL);
	}
	return (&clnt_res);
}

DmiUnregisterOUT *
_dmiunregister_0x1(DmiUnregisterIN *argp, CLIENT *clnt)
{
	static DmiUnregisterOUT clnt_res;

	memset((char *)&clnt_res, 0, sizeof (clnt_res));
	if (clnt_call(clnt, _DmiUnregister,
		(xdrproc_t) xdr_DmiUnregisterIN, (caddr_t) argp,
		(xdrproc_t) xdr_DmiUnregisterOUT, (caddr_t) &clnt_res,
		TIMEOUT) != RPC_SUCCESS) {
		return (NULL);
	}
	return (&clnt_res);
}

DmiGetVersionOUT *
_dmigetversion_0x1(DmiGetVersionIN *argp, CLIENT *clnt)
{
	static DmiGetVersionOUT clnt_res;

	memset((char *)&clnt_res, 0, sizeof (clnt_res));
	if (clnt_call(clnt, _DmiGetVersion,
		(xdrproc_t) xdr_DmiGetVersionIN, (caddr_t) argp,
		(xdrproc_t) xdr_DmiGetVersionOUT, (caddr_t) &clnt_res,
		TIMEOUT) != RPC_SUCCESS) {
		return (NULL);
	}
	return (&clnt_res);
}

DmiGetConfigOUT *
_dmigetconfig_0x1(DmiGetConfigIN *argp, CLIENT *clnt)
{
	static DmiGetConfigOUT clnt_res;

	memset((char *)&clnt_res, 0, sizeof (clnt_res));
	if (clnt_call(clnt, _DmiGetConfig,
		(xdrproc_t) xdr_DmiGetConfigIN, (caddr_t) argp,
		(xdrproc_t) xdr_DmiGetConfigOUT, (caddr_t) &clnt_res,
		TIMEOUT) != RPC_SUCCESS) {
		return (NULL);
	}
	return (&clnt_res);
}

DmiSetConfigOUT *
_dmisetconfig_0x1(DmiSetConfigIN *argp, CLIENT *clnt)
{
	static DmiSetConfigOUT clnt_res;

	memset((char *)&clnt_res, 0, sizeof (clnt_res));
	if (clnt_call(clnt, _DmiSetConfig,
		(xdrproc_t) xdr_DmiSetConfigIN, (caddr_t) argp,
		(xdrproc_t) xdr_DmiSetConfigOUT, (caddr_t) &clnt_res,
		TIMEOUT) != RPC_SUCCESS) {
		return (NULL);
	}
	return (&clnt_res);
}

DmiListComponentsOUT *
_dmilistcomponents_0x1(DmiListComponentsIN *argp, CLIENT *clnt)
{
	static DmiListComponentsOUT clnt_res;

	memset((char *)&clnt_res, 0, sizeof (clnt_res));
	if (clnt_call(clnt, _DmiListComponents,
		(xdrproc_t) xdr_DmiListComponentsIN, (caddr_t) argp,
		(xdrproc_t) xdr_DmiListComponentsOUT, (caddr_t) &clnt_res,
		TIMEOUT) != RPC_SUCCESS) {
		return (NULL);
	}
	return (&clnt_res);
}

DmiListComponentsByClassOUT *
_dmilistcomponentsbyclass_0x1(DmiListComponentsByClassIN *argp, CLIENT *clnt)
{
	static DmiListComponentsByClassOUT clnt_res;

	memset((char *)&clnt_res, 0, sizeof (clnt_res));
	if (clnt_call(clnt, _DmiListComponentsByClass,
		(xdrproc_t) xdr_DmiListComponentsByClassIN, (caddr_t) argp,
		(xdrproc_t) xdr_DmiListComponentsByClassOUT, (caddr_t) &clnt_res,
		TIMEOUT) != RPC_SUCCESS) {
		return (NULL);
	}
	return (&clnt_res);
}

DmiListLanguagesOUT *
_dmilistlanguages_0x1(DmiListLanguagesIN *argp, CLIENT *clnt)
{
	static DmiListLanguagesOUT clnt_res;

	memset((char *)&clnt_res, 0, sizeof (clnt_res));
	if (clnt_call(clnt, _DmiListLanguages,
		(xdrproc_t) xdr_DmiListLanguagesIN, (caddr_t) argp,
		(xdrproc_t) xdr_DmiListLanguagesOUT, (caddr_t) &clnt_res,
		TIMEOUT) != RPC_SUCCESS) {
		return (NULL);
	}
	return (&clnt_res);
}

DmiListClassNamesOUT *
_dmilistclassnames_0x1(DmiListClassNamesIN *argp, CLIENT *clnt)
{
	static DmiListClassNamesOUT clnt_res;

	memset((char *)&clnt_res, 0, sizeof (clnt_res));
	if (clnt_call(clnt, _DmiListClassNames,
		(xdrproc_t) xdr_DmiListClassNamesIN, (caddr_t) argp,
		(xdrproc_t) xdr_DmiListClassNamesOUT, (caddr_t) &clnt_res,
		TIMEOUT) != RPC_SUCCESS) {
		return (NULL);
	}
	return (&clnt_res);
}

DmiListGroupsOUT *
_dmilistgroups_0x1(DmiListGroupsIN *argp, CLIENT *clnt)
{
	static DmiListGroupsOUT clnt_res;

	memset((char *)&clnt_res, 0, sizeof (clnt_res));
	if (clnt_call(clnt, _DmiListGroups,
		(xdrproc_t) xdr_DmiListGroupsIN, (caddr_t) argp,
		(xdrproc_t) xdr_DmiListGroupsOUT, (caddr_t) &clnt_res,
		TIMEOUT) != RPC_SUCCESS) {
		return (NULL);
	}
	return (&clnt_res);
}

DmiListAttributesOUT *
_dmilistattributes_0x1(DmiListAttributesIN *argp, CLIENT *clnt)
{
	static DmiListAttributesOUT clnt_res;

	memset((char *)&clnt_res, 0, sizeof (clnt_res));
	if (clnt_call(clnt, _DmiListAttributes,
		(xdrproc_t) xdr_DmiListAttributesIN, (caddr_t) argp,
		(xdrproc_t) xdr_DmiListAttributesOUT, (caddr_t) &clnt_res,
		TIMEOUT) != RPC_SUCCESS) {
		return (NULL);
	}
	return (&clnt_res);
}

DmiAddRowOUT *
_dmiaddrow_0x1(DmiAddRowIN *argp, CLIENT *clnt)
{
	static DmiAddRowOUT clnt_res;

	memset((char *)&clnt_res, 0, sizeof (clnt_res));
	if (clnt_call(clnt, _DmiAddRow,
		(xdrproc_t) xdr_DmiAddRowIN, (caddr_t) argp,
		(xdrproc_t) xdr_DmiAddRowOUT, (caddr_t) &clnt_res,
		TIMEOUT) != RPC_SUCCESS) {
		return (NULL);
	}
	return (&clnt_res);
}

DmiDeleteRowOUT *
_dmideleterow_0x1(DmiDeleteRowIN *argp, CLIENT *clnt)
{
	static DmiDeleteRowOUT clnt_res;

	memset((char *)&clnt_res, 0, sizeof (clnt_res));
	if (clnt_call(clnt, _DmiDeleteRow,
		(xdrproc_t) xdr_DmiDeleteRowIN, (caddr_t) argp,
		(xdrproc_t) xdr_DmiDeleteRowOUT, (caddr_t) &clnt_res,
		TIMEOUT) != RPC_SUCCESS) {
		return (NULL);
	}
	return (&clnt_res);
}

DmiGetMultipleOUT *
_dmigetmultiple_0x1(DmiGetMultipleIN *argp, CLIENT *clnt)
{
	static DmiGetMultipleOUT clnt_res;

	memset((char *)&clnt_res, 0, sizeof (clnt_res));
	if (clnt_call(clnt, _DmiGetMultiple,
		(xdrproc_t) xdr_DmiGetMultipleIN, (caddr_t) argp,
		(xdrproc_t) xdr_DmiGetMultipleOUT, (caddr_t) &clnt_res,
		TIMEOUT) != RPC_SUCCESS) {
		return (NULL);
	}
	return (&clnt_res);
}

DmiSetMultipleOUT *
_dmisetmultiple_0x1(DmiSetMultipleIN *argp, CLIENT *clnt)
{
	static DmiSetMultipleOUT clnt_res;

	memset((char *)&clnt_res, 0, sizeof (clnt_res));
	if (clnt_call(clnt, _DmiSetMultiple,
		(xdrproc_t) xdr_DmiSetMultipleIN, (caddr_t) argp,
		(xdrproc_t) xdr_DmiSetMultipleOUT, (caddr_t) &clnt_res,
		TIMEOUT) != RPC_SUCCESS) {
		return (NULL);
	}
	return (&clnt_res);
}

DmiAddComponentOUT *
_dmiaddcomponent_0x1(DmiAddComponentIN *argp, CLIENT *clnt)
{
	static DmiAddComponentOUT clnt_res;

	memset((char *)&clnt_res, 0, sizeof (clnt_res));
	if (clnt_call(clnt, _DmiAddComponent,
		(xdrproc_t) xdr_DmiAddComponentIN, (caddr_t) argp,
		(xdrproc_t) xdr_DmiAddComponentOUT, (caddr_t) &clnt_res,
		TIMEOUT) != RPC_SUCCESS) {
		return (NULL);
	}
	return (&clnt_res);
}

DmiAddLanguageOUT *
_dmiaddlanguage_0x1(DmiAddLanguageIN *argp, CLIENT *clnt)
{
	static DmiAddLanguageOUT clnt_res;

	memset((char *)&clnt_res, 0, sizeof (clnt_res));
	if (clnt_call(clnt, _DmiAddLanguage,
		(xdrproc_t) xdr_DmiAddLanguageIN, (caddr_t) argp,
		(xdrproc_t) xdr_DmiAddLanguageOUT, (caddr_t) &clnt_res,
		TIMEOUT) != RPC_SUCCESS) {
		return (NULL);
	}
	return (&clnt_res);
}

DmiAddGroupOUT *
_dmiaddgroup_0x1(DmiAddGroupIN *argp, CLIENT *clnt)
{
	static DmiAddGroupOUT clnt_res;

	memset((char *)&clnt_res, 0, sizeof (clnt_res));
	if (clnt_call(clnt, _DmiAddGroup,
		(xdrproc_t) xdr_DmiAddGroupIN, (caddr_t) argp,
		(xdrproc_t) xdr_DmiAddGroupOUT, (caddr_t) &clnt_res,
		TIMEOUT) != RPC_SUCCESS) {
		return (NULL);
	}
	return (&clnt_res);
}

DmiDeleteComponentOUT *
_dmideletecomponent_0x1(DmiDeleteComponentIN *argp, CLIENT *clnt)
{
	static DmiDeleteComponentOUT clnt_res;

	memset((char *)&clnt_res, 0, sizeof (clnt_res));
	if (clnt_call(clnt, _DmiDeleteComponent,
		(xdrproc_t) xdr_DmiDeleteComponentIN, (caddr_t) argp,
		(xdrproc_t) xdr_DmiDeleteComponentOUT, (caddr_t) &clnt_res,
		TIMEOUT) != RPC_SUCCESS) {
		return (NULL);
	}
	return (&clnt_res);
}

DmiDeleteLanguageOUT *
_dmideletelanguage_0x1(DmiDeleteLanguageIN *argp, CLIENT *clnt)
{
	static DmiDeleteLanguageOUT clnt_res;

	memset((char *)&clnt_res, 0, sizeof (clnt_res));
	if (clnt_call(clnt, _DmiDeleteLanguage,
		(xdrproc_t) xdr_DmiDeleteLanguageIN, (caddr_t) argp,
		(xdrproc_t) xdr_DmiDeleteLanguageOUT, (caddr_t) &clnt_res,
		TIMEOUT) != RPC_SUCCESS) {
		return (NULL);
	}
	return (&clnt_res);
}

DmiDeleteGroupOUT *
_dmideletegroup_0x1(DmiDeleteGroupIN *argp, CLIENT *clnt)
{
	static DmiDeleteGroupOUT clnt_res;

	memset((char *)&clnt_res, 0, sizeof (clnt_res));
	if (clnt_call(clnt, _DmiDeleteGroup,
		(xdrproc_t) xdr_DmiDeleteGroupIN, (caddr_t) argp,
		(xdrproc_t) xdr_DmiDeleteGroupOUT, (caddr_t) &clnt_res,
		TIMEOUT) != RPC_SUCCESS) {
		return (NULL);
	}
	return (&clnt_res);
}

DmiGetAttributeOUT *
_dmigetattribute_0x1(DmiGetAttributeIN *argp, CLIENT *clnt)
{
	static DmiGetAttributeOUT clnt_res;

	memset((char *)&clnt_res, 0, sizeof (clnt_res));
	if (clnt_call(clnt, _DmiGetAttribute,
		(xdrproc_t) xdr_DmiGetAttributeIN, (caddr_t) argp,
		(xdrproc_t) xdr_DmiGetAttributeOUT, (caddr_t) &clnt_res,
		TIMEOUT) != RPC_SUCCESS) {
		return (NULL);
	}
	return (&clnt_res);
}

DmiSetAttributeOUT *
_dmisetattribute_0x1(DmiSetAttributeIN *argp, CLIENT *clnt)
{
	static DmiSetAttributeOUT clnt_res;

	memset((char *)&clnt_res, 0, sizeof (clnt_res));
	if (clnt_call(clnt, _DmiSetAttribute,
		(xdrproc_t) xdr_DmiSetAttributeIN, (caddr_t) argp,
		(xdrproc_t) xdr_DmiSetAttributeOUT, (caddr_t) &clnt_res,
		TIMEOUT) != RPC_SUCCESS) {
		return (NULL);
	}
	return (&clnt_res);
}

DmiRegisterCiOUT *
_dmiregisterci_0x1(DmiRegisterCiIN *argp, CLIENT *clnt)
{
	static DmiRegisterCiOUT clnt_res;

	memset((char *)&clnt_res, 0, sizeof (clnt_res));
	if (clnt_call(clnt, _DmiRegisterCi,
		(xdrproc_t) xdr_DmiRegisterCiIN, (caddr_t) argp,
		(xdrproc_t) xdr_DmiRegisterCiOUT, (caddr_t) &clnt_res,
		TIMEOUT) != RPC_SUCCESS) {
		return (NULL);
	}
	return (&clnt_res);
}

DmiUnregisterCiOUT *
_dmiunregisterci_0x1(DmiUnregisterCiIN *argp, CLIENT *clnt)
{
	static DmiUnregisterCiOUT clnt_res;

	memset((char *)&clnt_res, 0, sizeof (clnt_res));
	if (clnt_call(clnt, _DmiUnregisterCi,
		(xdrproc_t) xdr_DmiUnregisterCiIN, (caddr_t) argp,
		(xdrproc_t) xdr_DmiUnregisterCiOUT, (caddr_t) &clnt_res,
		TIMEOUT) != RPC_SUCCESS) {
		return (NULL);
	}
	return (&clnt_res);
}

DmiOriginateEventOUT *
_dmioriginateevent_0x1(DmiOriginateEventIN *argp, CLIENT *clnt)
{
	static DmiOriginateEventOUT clnt_res;

	memset((char *)&clnt_res, 0, sizeof (clnt_res));
	if (clnt_call(clnt, _DmiOriginateEvent,
		(xdrproc_t) xdr_DmiOriginateEventIN, (caddr_t) argp,
		(xdrproc_t) xdr_DmiOriginateEventOUT, (caddr_t) &clnt_res,
		TIMEOUT) != RPC_SUCCESS) {
		return (NULL);
	}
	return (&clnt_res);
}
