#
#ident	"@(#)Makefile	1.2	96/05/13 SMI"
#
# Copyright (c) 1995 by Sun Microsystems, Inc.
#

include ../Makefile.com

.KEEP_STATE:

all:		$(BLTDEFS) .WAIT $(DYNLIB)
install:	all $(ROOTDYNLIB)

include ../Makefile.targ
