#
# Copyright (c) 1997, by Sun Microsystems, Inc.
# All rights reserved.
#
#ident	"@(#)Makefile	1.3	97/08/28 SMI"
#
# lib/libkstat/sparcv9/Makefile

include ../Makefile.com
include ../../Makefile.lib.64

LIBS=	$(DYNLIB) $(LINTLIB)

.KEEP_STATE:

all: $(LIBS) 

install: all $(ROOTLIBS64) $(ROOTLINKS64)
