#
# Copyright (c) 1997, by Sun Microsystems, Inc.
# All rights reserved.
#
#prgma ident	"@(#)Makefile	1.2	97/10/09 SMI"
#
#
# lib/libposix4/sparcv9/Makefile

include ../Makefile.com
include ../../Makefile.lib.64

DYNFLAGS += $(DYNFLAGS64)

.KEEP_STATE:

install: all $(ROOTLIBS64) $(ROOTLINKS64)
