#
# Copyright (c) 1996-1997, by Sun Microsystems, Inc.
# All rights reserved.
#
#ident	"@(#)Makefile	1.6	97/12/24 SMI"
#
# cmd/sgs/libelf/sparcv9/Makefile

include		../Makefile.com

MISCOBJS=	$(MISCOBJS64)

.KEEP_STATE:

include		../Makefile.targ.64
