#
#pragma ident	"@(#)Makefile	1.3	97/08/31 SMI"
#
# Copyright (c) 1997 by Sun Microsystems, Inc.
#
# lib/libadm/i386/Makefile
#

include ../Makefile.com

.KEEP_STATE:

all:	$(LIBS) $(TXTS)

install: all $(ROOTLIBS) $(ROOTLINKS) $(ROOTLINT)
