#
# Copyright (c) 1996-1997 by Sun Microsystems, Inc.
# All rights reserved.
#
#ident	"@(#)Makefile	1.3	97/12/08 SMI"

include ../Makefile.com

.KEEP_STATE:

DATAFILES += depend i.initd

all: $(FILES) $(MACHDATAFILES)
install: all pkg

include ../Makefile.targ
