#
#ident	"@(#)Makefile	1.3	97/07/16 SMI"
#
# Copyright (c) 1997, by Sun Microsystems, Inc.
# All rights reserved.
#
# cmd/dmesg/sparc/Makefile

include ../Makefile.com
include ../../Makefile.cmd.64

install: all $(ROOTUSRSBINPROG64)
