#
#pragma ident	"@(#)Makefile	1.17	97/08/29 SMI"
#
# Copyright (c) 1995,1997 by Sun Microsystems, Inc.
# All rights reserved.
#
# libbsm/sparc/Makefile

include ../Makefile.com

.KEEP_STATE:

LIBS += 	$(DYNLIB) $(LINTLIB)

all: $(LIBS)

install: all $(ROOTLIBS) $(ROOTLINKS) $(ROOTLINT)
