#
#pragma ident	"@(#)Makefile.lib.sun	1.5	97/05/08 SMI"
#
include ../../../../../Makefile.cmd
CLEANFILES=lib$(LIB).a $(OBJS) $(COBJS) core

all: lib$(LIB).a

lib$(LIB).a: $(OBJS) $(COBJS) $(DEPLIBS)
	$(CCC) $(ALL_CXXFLAGS) $(CCFLAGS) $(CPPFLAGS) -xar -o $@ $(OBJS) $(COBJS) $(DEPLIBS)

install:
install-man:
depend: depend_src
depend.temp: $(GENSRCS)
gen: $(GENSRCS)
