#
#pragma ident	"@(#)Makefile.lib	1.3	97/05/08 SMI"
#

include ../../../../Makefile.cmd
CLEANFILES=lib$(LIB).a $(OBJS) $(COBJS) core
ALL_CXXFLAGS=$(CXXFLAGS) -I$(srcdir) -I$(srcdir)/../include $(INCLUDE) \
  $(DEFINES) $(PIC_FLAG)
ALL_CFLAGS=$(CFLAGS) $(DEBUG) $(OPTIMIZE) $(INCLUDE) $(DEFINES) $(PIC_FLAG)

all: lib$(LIB).a
pure: all

lib$(LIB).a: $(OBJS) $(COBJS)
	$(AR) r $@ $?
	$(RANLIB) $@

install:
install-man:
depend: depend_src
depend.temp: $(GENSRCS)
gen: $(GENSRCS)
