#
# Copyright (c) 1997, by Sun Microsystems, Inc.
# All rights reserved.
#
#ident	"@(#)Makefile.lib.64	1.1	97/05/15 SMI"

#
# Include overrides for library builds of 64-bit objects
#
include	$(SRC)/Makefile.master.64
