#
#ident	"@(#)Makefile	1.1	98/01/09 SMI"
#
# Copyright (c) 1993 - 1998, by Sun Microsystems, Inc.
# All rights reserved.
#

include ../Makefile.com

DATAFILES += depend

.KEEP_STATE:

all: $(FILES)
install: all pkg

include ../Makefile.targ
