/*****************************************************************************
 *****************************************************************************
 ****			WARNING
 ****	This file is automatically generated by the Epilogue Technology
 ****	 MIB compiler. Do NOT edit it by hand.
 ****
 **** Last build date: Wed Sep 25 15:19:55 1996
 ****	from file mib.cpp
 *****************************************************************************
 *****************************************************************************
 */


#define	_MIB	1
#include  <stdio.h>
#include  <sys/types.h>
#include  <sys/socket.h>
#include  <netinet/in.h>
#include  <netinet/in_systm.h>
#include  <netinet/ip.h>
#include  <netinet/ip_icmp.h>
#include  <net/if.h>
#include  <netinet/if_ether.h>
#include  <asn1.h>
#include  <mib.h>
#include  "general.h"
#include  "snmp.h"
#include  "snmpvars.h"
#define STATIC static

extern int it_exists();
extern int get_string();
extern int null_set_proc();
extern int std_next();
STATIC
MIBLEAF_T	sysDescr_leaf = LEAFM("sysDescr", VT_STRING,
			RO, it_exists,
			get_string, null_set_proc, std_next,
			snmp_sysDescr,
			0x0000, 0x0F, 0x0A);
extern int get_object_identifier();
STATIC
MIBLEAF_T	sysObjectID_leaf = LEAFM("sysObjectID", VT_OBJECT,
			RO, it_exists,
			get_object_identifier, null_set_proc, std_next,
			(char *)&snmp_sysObjectID,
			0x0000, 0x0F, 0x0A);
extern int get_sysUpTime();
STATIC
MIBLEAF_T	sysUpTime_leaf = LEAFM("sysUpTime", VT_TIMETICKS,
			RO, it_exists,
			get_sysUpTime, null_set_proc, std_next,
			(char *)NULL,
			0x0000, 0x0F, 0x0A);
extern int set_sysContact();
STATIC
MIBLEAF_T	sysContact_leaf = LEAFM("sysContact", VT_STRING,
			RW, it_exists,
			get_string, set_sysContact, std_next,
			(char *)snmp_sysContact,
			0x0000, 0x0F, 0x0A);
extern int get_sysName();
STATIC
MIBLEAF_T	sysName_leaf = LEAFM("sysName", VT_STRING,
			RO, it_exists,
			get_sysName, null_set_proc, std_next,
			(char *)NULL,
			0x0000, 0x0F, 0x0A);
extern int set_sysLocation();
STATIC
MIBLEAF_T	sysLocation_leaf = LEAFM("sysLocation", VT_STRING,
			RW, it_exists,
			get_string, set_sysLocation, std_next,
			(char *)snmp_sysLocation,
			0x0000, 0x0F, 0x0A);
extern int get_cookie();
STATIC
MIBLEAF_T	sysServices_leaf = LEAFM("sysServices", VT_NUMBER,
			RO, it_exists,
			get_cookie, null_set_proc, std_next,
			(char *)0x48,
			0x0000, 0x0F, 0x0A);
STATIC
MIBARC_T	system_arcs[] = {
			ARC(1, sysDescr_leaf),
			ARC(2, sysObjectID_leaf),
			ARC(3, sysUpTime_leaf),
			ARC(4, sysContact_leaf),
			ARC(5, sysName_leaf),
			ARC(6, sysLocation_leaf),
			ARC(7, sysServices_leaf),
			END_OF_ARC_LIST };
STATIC
MIBNODE_T	system_node = NODE("system", system_arcs);

extern int get_ifNumber();
STATIC
MIBLEAF_T	ifNumber_leaf = LEAFM("ifNumber", VT_NUMBER,
			RO, it_exists,
			get_ifNumber, null_set_proc, std_next,
			(char *)NULL,
			0x0000, 0x0C, 0x08);
extern int iftable_test();
extern int get_ifIndex();
extern int iftable_next();
STATIC
MIBLEAF_T	ifIndex_leaf = LEAFM("ifIndex", VT_NUMBER,
			RO, iftable_test,
			get_ifIndex, null_set_proc, iftable_next,
			(char *)NULL,
			0x0000, 0x0C, 0x08);
extern int get_ifDescr();
STATIC
MIBLEAF_T	ifDescr_leaf = LEAFM("ifDescr", VT_STRING,
			RO, iftable_test,
			get_ifDescr, null_set_proc, iftable_next,
			(char *)NULL,
			0x0000, 0x0C, 0x08);
extern int get_ifType();
STATIC
MIBLEAF_T	ifType_leaf = LEAFM("ifType", VT_NUMBER,
			RO, iftable_test,
			get_ifType, null_set_proc, iftable_next,
			(char *)NULL,
			0x0000, 0x0C, 0x08);
extern int get_ifMtu();
STATIC
MIBLEAF_T	ifMtu_leaf = LEAFM("ifMtu", VT_NUMBER,
			RO, iftable_test,
			get_ifMtu, null_set_proc, iftable_next,
			(char *)NULL,
			0x0000, 0x0C, 0x08);
extern int get_ifSpeed();
STATIC
MIBLEAF_T	ifSpeed_leaf = LEAFM("ifSpeed", VT_GAUGE,
			RO, iftable_test,
			get_ifSpeed, null_set_proc, iftable_next,
			(char *)NULL,
			0x0000, 0x0C, 0x08);
extern int get_ifPhysAddress();
STATIC
MIBLEAF_T	ifPhysAddress_leaf = LEAFM("ifPhysAddress", VT_STRING,
			RO, iftable_test,
			get_ifPhysAddress, null_set_proc, iftable_next,
			(char *)NULL,
			0x0000, 0x0C, 0x08);
extern int test_ifAdminStatus();
extern int get_ifAdminStatus();
extern int set_ifAdminStatus();
STATIC
MIBLEAF_T	ifAdminStatus_leaf = LEAFM("ifAdminStatus", VT_NUMBER,
			RW, test_ifAdminStatus,
			get_ifAdminStatus, set_ifAdminStatus, iftable_next,
			(char *)NULL,
			0x0000, 0x0C, 0x08);
extern int get_ifOperStatus();
STATIC
MIBLEAF_T	ifOperStatus_leaf = LEAFM("ifOperStatus", VT_NUMBER,
			RO, iftable_test,
			get_ifOperStatus, null_set_proc, iftable_next,
			(char *)NULL,
			0x0000, 0x0C, 0x08);
extern int get_ifLastChange();
STATIC
MIBLEAF_T	ifLastChange_leaf = LEAFM("ifLastChange", VT_TIMETICKS,
			RO, iftable_test,
			get_ifLastChange, null_set_proc, iftable_next,
			(char *)NULL,
			0x0000, 0x0C, 0x08);
extern int get_ifInOctets();
STATIC
MIBLEAF_T	ifInOctets_leaf = LEAFM("ifInOctets", VT_COUNTER,
			RO, iftable_test,
			get_ifInOctets, null_set_proc, iftable_next,
			(char *)0,
			0x0000, 0x0C, 0x08);
extern int get_ifInUcastPkts();
STATIC
MIBLEAF_T	ifInUcastPkts_leaf = LEAFM("ifInUcastPkts", VT_COUNTER,
			RO, iftable_test,
			get_ifInUcastPkts, null_set_proc, iftable_next,
			(char *)NULL,
			0x0000, 0x0C, 0x08);
extern int get_ifInNUcastPkts();
STATIC
MIBLEAF_T	ifInNUcastPkts_leaf = LEAFM("ifInNUcastPkts", VT_COUNTER,
			RO, iftable_test,
			get_ifInNUcastPkts, null_set_proc, iftable_next,
			(char *)0,
			0x0000, 0x0C, 0x08);
extern int get_ifInDiscards();
STATIC
MIBLEAF_T	ifInDiscards_leaf = LEAFM("ifInDiscards", VT_COUNTER,
			RO, iftable_test,
			get_ifInDiscards, null_set_proc, iftable_next,
			(char *)0,
			0x0000, 0x0C, 0x08);
extern int get_ifInErrors();
STATIC
MIBLEAF_T	ifInErrors_leaf = LEAFM("ifInErrors", VT_COUNTER,
			RO, iftable_test,
			get_ifInErrors, null_set_proc, iftable_next,
			(char *)NULL,
			0x0000, 0x0C, 0x08);
STATIC
MIBLEAF_T	ifInUnknownProtos_leaf = LEAFM("ifInUnknownProtos", VT_COUNTER,
			RO, iftable_test,
			get_cookie, null_set_proc, iftable_next,
			(char *)0,
			0x0000, 0x0C, 0x08);
extern int get_ifOutOctets();
STATIC
MIBLEAF_T	ifOutOctets_leaf = LEAFM("ifOutOctets", VT_COUNTER,
			RO, iftable_test,
			get_ifOutOctets, null_set_proc, iftable_next,
			(char *)0,
			0x0000, 0x0C, 0x08);
extern int get_ifOutUcastPkts();
STATIC
MIBLEAF_T	ifOutUcastPkts_leaf = LEAFM("ifOutUcastPkts", VT_COUNTER,
			RO, iftable_test,
			get_ifOutUcastPkts, null_set_proc, iftable_next,
			(char *)NULL,
			0x0000, 0x0C, 0x08);
extern int get_ifOutNUcastPkts();
STATIC
MIBLEAF_T	ifOutNUcastPkts_leaf = LEAFM("ifOutNUcastPkts", VT_COUNTER,
			RO, iftable_test,
			get_ifOutNUcastPkts, null_set_proc, iftable_next,
			(char *)0,
			0x0000, 0x0C, 0x08);
extern int get_ifOutDiscards();
STATIC
MIBLEAF_T	ifOutDiscards_leaf = LEAFM("ifOutDiscards", VT_COUNTER,
			RO, iftable_test,
			get_ifOutDiscards, null_set_proc, iftable_next,
			(char *)0,
			0x0000, 0x0C, 0x08);
extern int get_ifOutErrors();
STATIC
MIBLEAF_T	ifOutErrors_leaf = LEAFM("ifOutErrors", VT_COUNTER,
			RO, iftable_test,
			get_ifOutErrors, null_set_proc, iftable_next,
			(char *)NULL,
			0x0000, 0x0C, 0x08);
extern int get_ifOutQLen();
STATIC
MIBLEAF_T	ifOutQLen_leaf = LEAFM("ifOutQLen", VT_GAUGE,
			RO, iftable_test,
			get_ifOutQLen, null_set_proc, iftable_next,
			(char *)NULL,
			0x0000, 0x0C, 0x08);
extern int get_ifSpecific();
STATIC
MIBLEAF_T	ifSpecific_leaf = LEAFM("ifSpecific", VT_OBJECT,
			RO, iftable_test,
			get_ifSpecific, null_set_proc, iftable_next,
			(char *)NULL,
			0x0000, 0x0C, 0x08);
STATIC
MIBARC_T	ifEntry_arcs[] = {
			ARC(1, ifIndex_leaf),
			ARC(2, ifDescr_leaf),
			ARC(3, ifType_leaf),
			ARC(4, ifMtu_leaf),
			ARC(5, ifSpeed_leaf),
			ARC(6, ifPhysAddress_leaf),
			ARC(7, ifAdminStatus_leaf),
			ARC(8, ifOperStatus_leaf),
			ARC(9, ifLastChange_leaf),
			ARC(10, ifInOctets_leaf),
			ARC(11, ifInUcastPkts_leaf),
			ARC(12, ifInNUcastPkts_leaf),
			ARC(13, ifInDiscards_leaf),
			ARC(14, ifInErrors_leaf),
			ARC(15, ifInUnknownProtos_leaf),
			ARC(16, ifOutOctets_leaf),
			ARC(17, ifOutUcastPkts_leaf),
			ARC(18, ifOutNUcastPkts_leaf),
			ARC(19, ifOutDiscards_leaf),
			ARC(20, ifOutErrors_leaf),
			ARC(21, ifOutQLen_leaf),
			ARC(22, ifSpecific_leaf),
			END_OF_ARC_LIST };
STATIC
MIBNODE_T	ifEntry_node = NODE("ifEntry", ifEntry_arcs);

STATIC
MIBARC_T	ifTable_arcs[] = {
			ARC(1, ifEntry_node),
			END_OF_ARC_LIST };
STATIC
MIBNODE_T	ifTable_node = NODE("ifTable", ifTable_arcs);

STATIC
MIBARC_T	interfaces_arcs[] = {
			ARC(1, ifNumber_leaf),
			ARC(2, ifTable_node),
			END_OF_ARC_LIST };
STATIC
MIBNODE_T	interfaces_node = NODE("interfaces", interfaces_arcs);

extern int arptable_test();
extern int get_atIfIndex();
extern int arptable_next();
STATIC
MIBLEAF_T	atIfIndex_leaf = LEAFM("atIfIndex", VT_NUMBER,
			RO, arptable_test,
			get_atIfIndex, null_set_proc, arptable_next,
			(char *)NULL,
			0x0000, 0x0C, 0x08);
extern int get_atPhysAddress();
extern int set_atPhysAddress();
STATIC
MIBLEAF_T	atPhysAddress_leaf = LEAFM("atPhysAddress", VT_STRING,
			RW, arptable_test,
			get_atPhysAddress, set_atPhysAddress, arptable_next,
			(char *)NULL,
			0x0000, 0x0C, 0x08);
extern int get_atNetAddress();
STATIC
MIBLEAF_T	atNetAddress_leaf = LEAFM("atNetAddress", VT_IPADDRESS,
			RO, arptable_test,
			get_atNetAddress, null_set_proc, arptable_next,
			(char *)NULL,
			0x0000, 0x0C, 0x08);
STATIC
MIBARC_T	atEntry_arcs[] = {
			ARC(1, atIfIndex_leaf),
			ARC(2, atPhysAddress_leaf),
			ARC(3, atNetAddress_leaf),
			END_OF_ARC_LIST };
STATIC
MIBNODE_T	atEntry_node = NODE("atEntry", atEntry_arcs);

STATIC
MIBARC_T	atTable_arcs[] = {
			ARC(1, atEntry_node),
			END_OF_ARC_LIST };
STATIC
MIBNODE_T	atTable_node = NODE("atTable", atTable_arcs);

STATIC
MIBARC_T	at_arcs[] = {
			ARC(1, atTable_node),
			END_OF_ARC_LIST };
STATIC
MIBNODE_T	at_node = NODE("at", at_arcs);

extern int test_ipForwarding();
extern int get_ipForwarding();
extern int set_ipForwarding();
STATIC
MIBLEAF_T	ipForwarding_leaf = LEAFM("ipForwarding", VT_NUMBER,
			RW, test_ipForwarding,
			get_ipForwarding, set_ipForwarding, std_next,
			(char *)NULL,
			0x0000, 0x0C, 0x08);
extern int get_ipDefaultTTL();
STATIC
MIBLEAF_T	ipDefaultTTL_leaf = LEAFM("ipDefaultTTL", VT_NUMBER,
			RO, it_exists,
			get_ipDefaultTTL, null_set_proc, std_next,
			(char *)NULL,
			0x0000, 0x0C, 0x08);
extern int get_ip();
STATIC
MIBLEAF_T	ipInReceives_leaf = LEAFM("ipInReceives", VT_COUNTER,
			RO, it_exists,
			get_ip, null_set_proc, std_next,
			(char *)NULL,
			0x0000, 0x0C, 0x08);
STATIC
MIBLEAF_T	ipInHdrErrors_leaf = LEAFM("ipInHdrErrors", VT_COUNTER,
			RO, it_exists,
			get_ip, null_set_proc, std_next,
			(char *)NULL,
			0x0000, 0x0C, 0x08);
STATIC
MIBLEAF_T	ipInAddrErrors_leaf = LEAFM("ipInAddrErrors", VT_COUNTER,
			RO, it_exists,
			get_ip, null_set_proc, std_next,
			(char *)NULL,
			0x0000, 0x0C, 0x08);
STATIC
MIBLEAF_T	ipForwDatagrams_leaf = LEAFM("ipForwDatagrams", VT_COUNTER,
			RO, it_exists,
			get_ip, null_set_proc, std_next,
			(char *)NULL,
			0x0000, 0x0C, 0x08);
STATIC
MIBLEAF_T	ipInUnknownProtos_leaf = LEAFM("ipInUnknownProtos", VT_COUNTER,
			RO, it_exists,
			get_ip, null_set_proc, std_next,
			(char *)NULL,
			0x0000, 0x0C, 0x08);
STATIC
MIBLEAF_T	ipInDiscards_leaf = LEAFM("ipInDiscards", VT_COUNTER,
			RO, it_exists,
			get_ip, null_set_proc, std_next,
			(char *)NULL,
			0x0000, 0x0C, 0x08);
STATIC
MIBLEAF_T	ipInDelivers_leaf = LEAFM("ipInDelivers", VT_COUNTER,
			RO, it_exists,
			get_ip, null_set_proc, std_next,
			(char *)NULL,
			0x0000, 0x0C, 0x08);
STATIC
MIBLEAF_T	ipOutRequests_leaf = LEAFM("ipOutRequests", VT_COUNTER,
			RO, it_exists,
			get_ip, null_set_proc, std_next,
			(char *)NULL,
			0x0000, 0x0C, 0x08);
STATIC
MIBLEAF_T	ipOutDiscards_leaf = LEAFM("ipOutDiscards", VT_COUNTER,
			RO, it_exists,
			get_ip, null_set_proc, std_next,
			(char *)NULL,
			0x0000, 0x0C, 0x08);
STATIC
MIBLEAF_T	ipOutNoRoutes_leaf = LEAFM("ipOutNoRoutes", VT_COUNTER,
			RO, it_exists,
			get_ip, null_set_proc, std_next,
			(char *)NULL,
			0x0000, 0x0C, 0x08);
STATIC
MIBLEAF_T	ipReasmTimeout_leaf = LEAFM("ipReasmTimeout", VT_NUMBER,
			RO, it_exists,
			get_ip, null_set_proc, std_next,
			(char *)NULL,
			0x0000, 0x0C, 0x08);
STATIC
MIBLEAF_T	ipReasmReqds_leaf = LEAFM("ipReasmReqds", VT_COUNTER,
			RO, it_exists,
			get_ip, null_set_proc, std_next,
			(char *)NULL,
			0x0000, 0x0C, 0x08);
STATIC
MIBLEAF_T	ipReasmOKs_leaf = LEAFM("ipReasmOKs", VT_COUNTER,
			RO, it_exists,
			get_ip, null_set_proc, std_next,
			(char *)NULL,
			0x0000, 0x0C, 0x08);
STATIC
MIBLEAF_T	ipReasmFails_leaf = LEAFM("ipReasmFails", VT_COUNTER,
			RO, it_exists,
			get_ip, null_set_proc, std_next,
			(char *)NULL,
			0x0000, 0x0C, 0x08);
STATIC
MIBLEAF_T	ipFragOKs_leaf = LEAFM("ipFragOKs", VT_COUNTER,
			RO, it_exists,
			get_ip, null_set_proc, std_next,
			(char *)NULL,
			0x0000, 0x0C, 0x08);
STATIC
MIBLEAF_T	ipFragFails_leaf = LEAFM("ipFragFails", VT_COUNTER,
			RO, it_exists,
			get_ip, null_set_proc, std_next,
			(char *)NULL,
			0x0000, 0x0C, 0x08);
STATIC
MIBLEAF_T	ipFragCreates_leaf = LEAFM("ipFragCreates", VT_COUNTER,
			RO, it_exists,
			get_ip, null_set_proc, std_next,
			(char *)NULL,
			0x0000, 0x0C, 0x08);
extern int ipadtable_test();
extern int get_ipAdEntAddr();
extern int ipadtable_next();
STATIC
MIBLEAF_T	ipAdEntAddr_leaf = LEAFM("ipAdEntAddr", VT_IPADDRESS,
			RO, ipadtable_test,
			get_ipAdEntAddr, null_set_proc, ipadtable_next,
			(char *)NULL,
			0x0000, 0x0C, 0x08);
extern int get_ipAdEntIfIndex();
STATIC
MIBLEAF_T	ipAdEntIfIndex_leaf = LEAFM("ipAdEntIfIndex", VT_NUMBER,
			RO, ipadtable_test,
			get_ipAdEntIfIndex, null_set_proc, ipadtable_next,
			(char *)NULL,
			0x0000, 0x0C, 0x08);
extern int get_ipAdEntNetMask();
STATIC
MIBLEAF_T	ipAdEntNetMask_leaf = LEAFM("ipAdEntNetMask", VT_IPADDRESS,
			RO, ipadtable_test,
			get_ipAdEntNetMask, null_set_proc, ipadtable_next,
			(char *)NULL,
			0x0000, 0x0C, 0x08);
STATIC
MIBLEAF_T	ipAdEntBcastAddr_leaf = LEAFM("ipAdEntBcastAddr", VT_NUMBER,
			RO, ipadtable_test,
			get_cookie, null_set_proc, ipadtable_next,
			(char *)1,
			0x0000, 0x0C, 0x08);
STATIC
MIBLEAF_T	ipAdEntReasmMaxSiz_leaf = LEAFM("ipAdEntReasmMaxSiz", VT_NUMBER,
			RO, ipadtable_test,
			get_cookie, null_set_proc, ipadtable_next,
			(char *)65535,
			0x0000, 0x0C, 0x08);
STATIC
MIBARC_T	ipAddrEntry_arcs[] = {
			ARC(1, ipAdEntAddr_leaf),
			ARC(2, ipAdEntIfIndex_leaf),
			ARC(3, ipAdEntNetMask_leaf),
			ARC(4, ipAdEntBcastAddr_leaf),
			ARC(5, ipAdEntReasmMaxSiz_leaf),
			END_OF_ARC_LIST };
STATIC
MIBNODE_T	ipAddrEntry_node = NODE("ipAddrEntry", ipAddrEntry_arcs);

STATIC
MIBARC_T	ipAddrTable_arcs[] = {
			ARC(1, ipAddrEntry_node),
			END_OF_ARC_LIST };
STATIC
MIBNODE_T	ipAddrTable_node = NODE("ipAddrTable", ipAddrTable_arcs);

extern int test_ipRouteEntry();
extern int get_ipRouteDest();
extern int next_ipRouteEntry();
STATIC
MIBLEAF_T	ipRouteDest_leaf = LEAFM("ipRouteDest", VT_IPADDRESS,
			RW, test_ipRouteEntry,
			get_ipRouteDest, null_set_proc, next_ipRouteEntry,
			(char *)0,
			101, 0x0C, 0x08);
extern int get_ipRouteIfIndex();
STATIC
MIBLEAF_T	ipRouteIfIndex_leaf = LEAFM("ipRouteIfIndex", VT_NUMBER,
			RW, test_ipRouteEntry,
			get_ipRouteIfIndex, null_set_proc, next_ipRouteEntry,
			(char *)0,
			102, 0x0C, 0x08);
STATIC
MIBLEAF_T	ipRouteMetric1_leaf = LEAFM("ipRouteMetric1", VT_NUMBER,
			RW, test_ipRouteEntry,
			get_cookie, null_set_proc, next_ipRouteEntry,
			(char *)-1,
			103, 0x0C, 0x08);
STATIC
MIBLEAF_T	ipRouteMetric2_leaf = LEAFM("ipRouteMetric2", VT_NUMBER,
			RW, test_ipRouteEntry,
			get_cookie, null_set_proc, next_ipRouteEntry,
			(char *)-1,
			104, 0x0C, 0x08);
STATIC
MIBLEAF_T	ipRouteMetric3_leaf = LEAFM("ipRouteMetric3", VT_NUMBER,
			RW, test_ipRouteEntry,
			get_cookie, null_set_proc, next_ipRouteEntry,
			(char *)-1,
			105, 0x0C, 0x08);
STATIC
MIBLEAF_T	ipRouteMetric4_leaf = LEAFM("ipRouteMetric4", VT_NUMBER,
			RW, test_ipRouteEntry,
			get_cookie, null_set_proc, next_ipRouteEntry,
			(char *)-1,
			106, 0x0C, 0x08);
extern int get_ipRouteNextHop();
extern int set_ipRouteNextHop();
STATIC
MIBLEAF_T	ipRouteNextHop_leaf = LEAFM("ipRouteNextHop", VT_IPADDRESS,
			RW, test_ipRouteEntry,
			get_ipRouteNextHop, set_ipRouteNextHop, next_ipRouteEntry,
			(char *)0,
			107, 0x0C, 0x08);
extern int get_ipRouteType();
extern int set_ipRouteType();
STATIC
MIBLEAF_T	ipRouteType_leaf = LEAFM("ipRouteType", VT_NUMBER,
			RW, test_ipRouteEntry,
			get_ipRouteType, set_ipRouteType, next_ipRouteEntry,
			(char *)0,
			108, 0x0C, 0x08);
extern int get_ipRouteProto();
STATIC
MIBLEAF_T	ipRouteProto_leaf = LEAFM("ipRouteProto", VT_NUMBER,
			RO, test_ipRouteEntry,
			get_ipRouteProto, null_set_proc, next_ipRouteEntry,
			(char *)0,
			109, 0x0C, 0x08);
STATIC
MIBLEAF_T	ipRouteAge_leaf = LEAFM("ipRouteAge", VT_NUMBER,
			RW, test_ipRouteEntry,
			get_cookie, null_set_proc, next_ipRouteEntry,
			(char *)0,
			110, 0x0C, 0x08);
extern int get_ipRouteMask();
STATIC
MIBLEAF_T	ipRouteMask_leaf = LEAFM("ipRouteMask", VT_IPADDRESS,
			RW, test_ipRouteEntry,
			get_ipRouteMask, null_set_proc, next_ipRouteEntry,
			(char *)0,
			111, 0x0C, 0x08);
STATIC
MIBLEAF_T	ipRouteMetric5_leaf = LEAFM("ipRouteMetric5", VT_NUMBER,
			RW, test_ipRouteEntry,
			get_cookie, null_set_proc, next_ipRouteEntry,
			(char *)-1,
			112, 0x0C, 0x08);
extern int get_ipRouteInfo();
STATIC
MIBLEAF_T	ipRouteInfo_leaf = LEAFM("ipRouteInfo", VT_OBJECT,
			RO, test_ipRouteEntry,
			get_ipRouteInfo, null_set_proc, next_ipRouteEntry,
			(char *)0,
			113, 0x0C, 0x08);
STATIC
MIBARC_T	ipRouteEntry_arcs[] = {
			ARC(1, ipRouteDest_leaf),
			ARC(2, ipRouteIfIndex_leaf),
			ARC(3, ipRouteMetric1_leaf),
			ARC(4, ipRouteMetric2_leaf),
			ARC(5, ipRouteMetric3_leaf),
			ARC(6, ipRouteMetric4_leaf),
			ARC(7, ipRouteNextHop_leaf),
			ARC(8, ipRouteType_leaf),
			ARC(9, ipRouteProto_leaf),
			ARC(10, ipRouteAge_leaf),
			ARC(11, ipRouteMask_leaf),
			ARC(12, ipRouteMetric5_leaf),
			ARC(13, ipRouteInfo_leaf),
			END_OF_ARC_LIST };
STATIC
MIBNODE_T	ipRouteEntry_node = NODE("ipRouteEntry", ipRouteEntry_arcs);

STATIC
MIBARC_T	ipRoutingTable_arcs[] = {
			ARC(1, ipRouteEntry_node),
			END_OF_ARC_LIST };
STATIC
MIBNODE_T	ipRoutingTable_node = NODE("ipRoutingTable", ipRoutingTable_arcs);

extern int n2mtable_test();
extern int get_n2mIfIndex();
extern int n2mtable_next();
STATIC
MIBLEAF_T	ipNetToMediaIfIndex_leaf = LEAFM("ipNetToMediaIfIndex", VT_NUMBER,
			RO, n2mtable_test,
			get_n2mIfIndex, null_set_proc, n2mtable_next,
			(char *)NULL,
			0x0000, 0x0C, 0x08);
extern int get_n2mPhysAddress();
extern int set_n2mPhysAddress();
STATIC
MIBLEAF_T	ipNetToMediaPhysAddress_leaf = LEAFM("ipNetToMediaPhysAddress", VT_STRING,
			RW, n2mtable_test,
			get_n2mPhysAddress, set_n2mPhysAddress, n2mtable_next,
			(char *)NULL,
			0x0000, 0x0C, 0x08);
extern int get_n2mNetAddress();
STATIC
MIBLEAF_T	ipNetToMediaNetAddress_leaf = LEAFM("ipNetToMediaNetAddress", VT_IPADDRESS,
			RO, n2mtable_test,
			get_n2mNetAddress, null_set_proc, n2mtable_next,
			(char *)NULL,
			0x0000, 0x0C, 0x08);
extern int set_ipNetToMediaType();
STATIC
MIBLEAF_T	ipNetToMediaType_leaf = LEAFM("ipNetToMediaType", VT_NUMBER,
			RW, n2mtable_test,
			get_cookie, set_ipNetToMediaType, n2mtable_next,
			(char *)3,
			0x0000, 0x0C, 0x08);
STATIC
MIBARC_T	ipNetToMediaEntry_arcs[] = {
			ARC(1, ipNetToMediaIfIndex_leaf),
			ARC(2, ipNetToMediaPhysAddress_leaf),
			ARC(3, ipNetToMediaNetAddress_leaf),
			ARC(4, ipNetToMediaType_leaf),
			END_OF_ARC_LIST };
STATIC
MIBNODE_T	ipNetToMediaEntry_node = NODE("ipNetToMediaEntry", ipNetToMediaEntry_arcs);

STATIC
MIBARC_T	ipNetToMediaTable_arcs[] = {
			ARC(1, ipNetToMediaEntry_node),
			END_OF_ARC_LIST };
STATIC
MIBNODE_T	ipNetToMediaTable_node = NODE("ipNetToMediaTable", ipNetToMediaTable_arcs);

STATIC
MIBLEAF_T	ipRoutingDiscards_leaf = LEAFM("ipRoutingDiscards", VT_COUNTER,
			RO, it_exists,
			get_cookie, null_set_proc, std_next,
			(char *)0,
			0x0000, 0x0C, 0x08);
STATIC
MIBARC_T	ip_arcs[] = {
			ARC(1, ipForwarding_leaf),
			ARC(2, ipDefaultTTL_leaf),
			ARC(3, ipInReceives_leaf),
			ARC(4, ipInHdrErrors_leaf),
			ARC(5, ipInAddrErrors_leaf),
			ARC(6, ipForwDatagrams_leaf),
			ARC(7, ipInUnknownProtos_leaf),
			ARC(8, ipInDiscards_leaf),
			ARC(9, ipInDelivers_leaf),
			ARC(10, ipOutRequests_leaf),
			ARC(11, ipOutDiscards_leaf),
			ARC(12, ipOutNoRoutes_leaf),
			ARC(13, ipReasmTimeout_leaf),
			ARC(14, ipReasmReqds_leaf),
			ARC(15, ipReasmOKs_leaf),
			ARC(16, ipReasmFails_leaf),
			ARC(17, ipFragOKs_leaf),
			ARC(18, ipFragFails_leaf),
			ARC(19, ipFragCreates_leaf),
			ARC(20, ipAddrTable_node),
			ARC(21, ipRoutingTable_node),
			ARC(22, ipNetToMediaTable_node),
			ARC(23, ipRoutingDiscards_leaf),
			END_OF_ARC_LIST };
STATIC
MIBNODE_T	ip_node = NODE("ip", ip_arcs);

extern int get_icmpInMsgs();
STATIC
MIBLEAF_T	icmpInMsgs_leaf = LEAFM("icmpInMsgs", VT_COUNTER,
			RO, it_exists,
			get_icmpInMsgs, null_set_proc, std_next,
			(char *)NULL,
			0x0000, 0x0C, 0x08);
extern int get_icmpInErrors();
STATIC
MIBLEAF_T	icmpInErrors_leaf = LEAFM("icmpInErrors", VT_COUNTER,
			RO, it_exists,
			get_icmpInErrors, null_set_proc, std_next,
			(char *)NULL,
			0x0000, 0x0C, 0x08);
extern int icmpin();
STATIC
MIBLEAF_T	icmpInDestUnreachs_leaf = LEAFM("icmpInDestUnreachs", VT_COUNTER,
			RO, it_exists,
			icmpin, null_set_proc, std_next,
			(char *)ICMP_UNREACH,
			0x0000, 0x0C, 0x08);
STATIC
MIBLEAF_T	icmpInTimeExcds_leaf = LEAFM("icmpInTimeExcds", VT_COUNTER,
			RO, it_exists,
			icmpin, null_set_proc, std_next,
			(char *)ICMP_TIMXCEED,
			0x0000, 0x0C, 0x08);
STATIC
MIBLEAF_T	icmpInParmProbs_leaf = LEAFM("icmpInParmProbs", VT_COUNTER,
			RO, it_exists,
			icmpin, null_set_proc, std_next,
			(char *)ICMP_PARAMPROB,
			0x0000, 0x0C, 0x08);
STATIC
MIBLEAF_T	icmpInSrcQuenchs_leaf = LEAFM("icmpInSrcQuenchs", VT_COUNTER,
			RO, it_exists,
			icmpin, null_set_proc, std_next,
			(char *)ICMP_SOURCEQUENCH,
			0x0000, 0x0C, 0x08);
STATIC
MIBLEAF_T	icmpInRedirects_leaf = LEAFM("icmpInRedirects", VT_COUNTER,
			RO, it_exists,
			icmpin, null_set_proc, std_next,
			(char *)ICMP_REDIRECT,
			0x0000, 0x0C, 0x08);
STATIC
MIBLEAF_T	icmpInEchos_leaf = LEAFM("icmpInEchos", VT_COUNTER,
			RO, it_exists,
			icmpin, null_set_proc, std_next,
			(char *)ICMP_ECHO,
			0x0000, 0x0C, 0x08);
STATIC
MIBLEAF_T	icmpInEchoReps_leaf = LEAFM("icmpInEchoReps", VT_COUNTER,
			RO, it_exists,
			icmpin, null_set_proc, std_next,
			(char *)ICMP_ECHOREPLY,
			0x0000, 0x0C, 0x08);
STATIC
MIBLEAF_T	icmpInTimestamps_leaf = LEAFM("icmpInTimestamps", VT_COUNTER,
			RO, it_exists,
			icmpin, null_set_proc, std_next,
			(char *)ICMP_TSTAMP,
			0x0000, 0x0C, 0x08);
STATIC
MIBLEAF_T	icmpInTimestampReps_leaf = LEAFM("icmpInTimestampReps", VT_COUNTER,
			RO, it_exists,
			icmpin, null_set_proc, std_next,
			(char *)ICMP_TSTAMPREPLY,
			0x0000, 0x0C, 0x08);
STATIC
MIBLEAF_T	icmpInAddrMasks_leaf = LEAFM("icmpInAddrMasks", VT_COUNTER,
			RO, it_exists,
			icmpin, null_set_proc, std_next,
			(char *)ICMP_MASKREQ,
			0x0000, 0x0C, 0x08);
STATIC
MIBLEAF_T	icmpInAddrMaskReps_leaf = LEAFM("icmpInAddrMaskReps", VT_COUNTER,
			RO, it_exists,
			icmpin, null_set_proc, std_next,
			(char *)ICMP_MASKREPLY,
			0x0000, 0x0C, 0x08);
extern int get_icmpOutMsgs();
STATIC
MIBLEAF_T	icmpOutMsgs_leaf = LEAFM("icmpOutMsgs", VT_COUNTER,
			RO, it_exists,
			get_icmpOutMsgs, null_set_proc, std_next,
			(char *)NULL,
			0x0000, 0x0C, 0x08);
extern int get_icmpOutErrors();
STATIC
MIBLEAF_T	icmpOutErrors_leaf = LEAFM("icmpOutErrors", VT_COUNTER,
			RO, it_exists,
			get_icmpOutErrors, null_set_proc, std_next,
			(char *)NULL,
			0x0000, 0x0C, 0x08);
extern int icmpout();
STATIC
MIBLEAF_T	icmpOutDestUnreachs_leaf = LEAFM("icmpOutDestUnreachs", VT_COUNTER,
			RO, it_exists,
			icmpout, null_set_proc, std_next,
			(char *)ICMP_UNREACH,
			0x0000, 0x0C, 0x08);
STATIC
MIBLEAF_T	icmpOutTimeExcds_leaf = LEAFM("icmpOutTimeExcds", VT_COUNTER,
			RO, it_exists,
			icmpout, null_set_proc, std_next,
			(char *)ICMP_TIMXCEED,
			0x0000, 0x0C, 0x08);
STATIC
MIBLEAF_T	icmpOutParmProbs_leaf = LEAFM("icmpOutParmProbs", VT_COUNTER,
			RO, it_exists,
			icmpout, null_set_proc, std_next,
			(char *)ICMP_PARAMPROB,
			0x0000, 0x0C, 0x08);
STATIC
MIBLEAF_T	icmpOutSrcQuenchs_leaf = LEAFM("icmpOutSrcQuenchs", VT_COUNTER,
			RO, it_exists,
			icmpout, null_set_proc, std_next,
			(char *)ICMP_SOURCEQUENCH,
			0x0000, 0x0C, 0x08);
STATIC
MIBLEAF_T	icmpOutRedirects_leaf = LEAFM("icmpOutRedirects", VT_COUNTER,
			RO, it_exists,
			icmpout, null_set_proc, std_next,
			(char *)ICMP_REDIRECT,
			0x0000, 0x0C, 0x08);
STATIC
MIBLEAF_T	icmpOutEchos_leaf = LEAFM("icmpOutEchos", VT_COUNTER,
			RO, it_exists,
			icmpout, null_set_proc, std_next,
			(char *)ICMP_ECHO,
			0x0000, 0x0C, 0x08);
STATIC
MIBLEAF_T	icmpOutEchoReps_leaf = LEAFM("icmpOutEchoReps", VT_COUNTER,
			RO, it_exists,
			icmpout, null_set_proc, std_next,
			(char *)ICMP_ECHOREPLY,
			0x0000, 0x0C, 0x08);
STATIC
MIBLEAF_T	icmpOutTimestamps_leaf = LEAFM("icmpOutTimestamps", VT_COUNTER,
			RO, it_exists,
			icmpout, null_set_proc, std_next,
			(char *)ICMP_TSTAMP,
			0x0000, 0x0C, 0x08);
STATIC
MIBLEAF_T	icmpOutTimestampReps_leaf = LEAFM("icmpOutTimestampReps", VT_COUNTER,
			RO, it_exists,
			icmpout, null_set_proc, std_next,
			(char *)ICMP_TSTAMPREPLY,
			0x0000, 0x0C, 0x08);
STATIC
MIBLEAF_T	icmpOutAddrMasks_leaf = LEAFM("icmpOutAddrMasks", VT_COUNTER,
			RO, it_exists,
			icmpout, null_set_proc, std_next,
			(char *)ICMP_MASKREQ,
			0x0000, 0x0C, 0x08);
STATIC
MIBLEAF_T	icmpOutAddrMaskReps_leaf = LEAFM("icmpOutAddrMaskReps", VT_COUNTER,
			RO, it_exists,
			icmpout, null_set_proc, std_next,
			(char *)ICMP_MASKREPLY,
			0x0000, 0x0C, 0x08);
STATIC
MIBARC_T	icmp_arcs[] = {
			ARC(1, icmpInMsgs_leaf),
			ARC(2, icmpInErrors_leaf),
			ARC(3, icmpInDestUnreachs_leaf),
			ARC(4, icmpInTimeExcds_leaf),
			ARC(5, icmpInParmProbs_leaf),
			ARC(6, icmpInSrcQuenchs_leaf),
			ARC(7, icmpInRedirects_leaf),
			ARC(8, icmpInEchos_leaf),
			ARC(9, icmpInEchoReps_leaf),
			ARC(10, icmpInTimestamps_leaf),
			ARC(11, icmpInTimestampReps_leaf),
			ARC(12, icmpInAddrMasks_leaf),
			ARC(13, icmpInAddrMaskReps_leaf),
			ARC(14, icmpOutMsgs_leaf),
			ARC(15, icmpOutErrors_leaf),
			ARC(16, icmpOutDestUnreachs_leaf),
			ARC(17, icmpOutTimeExcds_leaf),
			ARC(18, icmpOutParmProbs_leaf),
			ARC(19, icmpOutSrcQuenchs_leaf),
			ARC(20, icmpOutRedirects_leaf),
			ARC(21, icmpOutEchos_leaf),
			ARC(22, icmpOutEchoReps_leaf),
			ARC(23, icmpOutTimestamps_leaf),
			ARC(24, icmpOutTimestampReps_leaf),
			ARC(25, icmpOutAddrMasks_leaf),
			ARC(26, icmpOutAddrMaskReps_leaf),
			END_OF_ARC_LIST };
STATIC
MIBNODE_T	icmp_node = NODE("icmp", icmp_arcs);

extern int get_tcp_ints();
STATIC
MIBLEAF_T	tcpRtoAlgorithm_leaf = LEAFM("tcpRtoAlgorithm", VT_NUMBER,
			RO, it_exists,
			get_tcp_ints, null_set_proc, std_next,
			(char *)NULL,
			0x0000, 0x0C, 0x08);
STATIC
MIBLEAF_T	tcpRtoMin_leaf = LEAFM("tcpRtoMin", VT_NUMBER,
			RO, it_exists,
			get_tcp_ints, null_set_proc, std_next,
			(char *)NULL,
			0x0000, 0x0C, 0x08);
STATIC
MIBLEAF_T	tcpRtoMax_leaf = LEAFM("tcpRtoMax", VT_NUMBER,
			RO, it_exists,
			get_tcp_ints, null_set_proc, std_next,
			(char *)NULL,
			0x0000, 0x0C, 0x08);
STATIC
MIBLEAF_T	tcpMaxConn_leaf = LEAFM("tcpMaxConn", VT_NUMBER,
			RO, it_exists,
			get_tcp_ints, null_set_proc, std_next,
			(char *)NULL,
			0x0000, 0x0C, 0x08);
extern int get_tcp_uints();
STATIC
MIBLEAF_T	tcpActiveOpens_leaf = LEAFM("tcpActiveOpens", VT_COUNTER,
			RO, it_exists,
			get_tcp_uints, null_set_proc, std_next,
			(char *)NULL,
			0x0000, 0x0C, 0x08);
STATIC
MIBLEAF_T	tcpPassiveOpens_leaf = LEAFM("tcpPassiveOpens", VT_COUNTER,
			RO, it_exists,
			get_tcp_uints, null_set_proc, std_next,
			(char *)NULL,
			0x0000, 0x0C, 0x08);
STATIC
MIBLEAF_T	tcpAttemptFails_leaf = LEAFM("tcpAttemptFails", VT_COUNTER,
			RO, it_exists,
			get_tcp_uints, null_set_proc, std_next,
			(char *)NULL,
			0x0000, 0x0C, 0x08);
STATIC
MIBLEAF_T	tcpEstabResets_leaf = LEAFM("tcpEstabResets", VT_COUNTER,
			RO, it_exists,
			get_tcp_uints, null_set_proc, std_next,
			(char *)NULL,
			0x0000, 0x0C, 0x08);
extern int get_tcpCurrEstab();
STATIC
MIBLEAF_T	tcpCurrEstab_leaf = LEAFM("tcpCurrEstab", VT_GAUGE,
			RO, it_exists,
			get_tcpCurrEstab, null_set_proc, std_next,
			(char *)NULL,
			0x0000, 0x0C, 0x08);
STATIC
MIBLEAF_T	tcpInSegs_leaf = LEAFM("tcpInSegs", VT_COUNTER,
			RO, it_exists,
			get_tcp_uints, null_set_proc, std_next,
			(char *)NULL,
			0x0000, 0x0C, 0x08);
STATIC
MIBLEAF_T	tcpOutSegs_leaf = LEAFM("tcpOutSegs", VT_COUNTER,
			RO, it_exists,
			get_tcp_uints, null_set_proc, std_next,
			(char *)NULL,
			0x0000, 0x0C, 0x08);
STATIC
MIBLEAF_T	tcpRetransSegs_leaf = LEAFM("tcpRetransSegs", VT_COUNTER,
			RO, it_exists,
			get_tcp_uints, null_set_proc, std_next,
			(char *)NULL,
			0x0000, 0x0C, 0x08);
extern int tcptable_test();
extern int get_tcpConnState();
extern int tcptable_next();
STATIC
MIBLEAF_T	tcpConnState_leaf = LEAFM("tcpConnState", VT_NUMBER,
			RW, tcptable_test,
			get_tcpConnState, null_set_proc, tcptable_next,
			(char *)NULL,
			0x0000, 0x0C, 0x08);
extern int get_tcptab_localaddr();
STATIC
MIBLEAF_T	tcpConnLocalAddress_leaf = LEAFM("tcpConnLocalAddress", VT_IPADDRESS,
			RO, tcptable_test,
			get_tcptab_localaddr, null_set_proc, tcptable_next,
			(char *)NULL,
			0x0000, 0x0C, 0x08);
extern int get_tcptab_localport();
STATIC
MIBLEAF_T	tcpConnLocalPort_leaf = LEAFM("tcpConnLocalPort", VT_NUMBER,
			RO, tcptable_test,
			get_tcptab_localport, null_set_proc, tcptable_next,
			(char *)NULL,
			0x0000, 0x0C, 0x08);
extern int get_tcptab_remoteaddr();
STATIC
MIBLEAF_T	tcpConnRemAddress_leaf = LEAFM("tcpConnRemAddress", VT_IPADDRESS,
			RO, tcptable_test,
			get_tcptab_remoteaddr, null_set_proc, tcptable_next,
			(char *)NULL,
			0x0000, 0x0C, 0x08);
extern int get_tcptab_remoteport();
STATIC
MIBLEAF_T	tcpConnRemPort_leaf = LEAFM("tcpConnRemPort", VT_NUMBER,
			RO, tcptable_test,
			get_tcptab_remoteport, null_set_proc, tcptable_next,
			(char *)NULL,
			0x0000, 0x0C, 0x08);
STATIC
MIBARC_T	tcpConnEntry_arcs[] = {
			ARC(1, tcpConnState_leaf),
			ARC(2, tcpConnLocalAddress_leaf),
			ARC(3, tcpConnLocalPort_leaf),
			ARC(4, tcpConnRemAddress_leaf),
			ARC(5, tcpConnRemPort_leaf),
			END_OF_ARC_LIST };
STATIC
MIBNODE_T	tcpConnEntry_node = NODE("tcpConnEntry", tcpConnEntry_arcs);

STATIC
MIBARC_T	tcpConnTable_arcs[] = {
			ARC(1, tcpConnEntry_node),
			END_OF_ARC_LIST };
STATIC
MIBNODE_T	tcpConnTable_node = NODE("tcpConnTable", tcpConnTable_arcs);

STATIC
MIBLEAF_T	tcpInErrs_leaf = LEAFM("tcpInErrs", VT_COUNTER,
			RO, it_exists,
			get_tcp_uints, null_set_proc, std_next,
			(char *)NULL,
			0x0000, 0x0C, 0x08);
STATIC
MIBLEAF_T	tcpOutRsts_leaf = LEAFM("tcpOutRsts", VT_COUNTER,
			RO, it_exists,
			get_tcp_uints, null_set_proc, std_next,
			(char *)NULL,
			0x0000, 0x0C, 0x08);
STATIC
MIBARC_T	tcp_arcs[] = {
			ARC(1, tcpRtoAlgorithm_leaf),
			ARC(2, tcpRtoMin_leaf),
			ARC(3, tcpRtoMax_leaf),
			ARC(4, tcpMaxConn_leaf),
			ARC(5, tcpActiveOpens_leaf),
			ARC(6, tcpPassiveOpens_leaf),
			ARC(7, tcpAttemptFails_leaf),
			ARC(8, tcpEstabResets_leaf),
			ARC(9, tcpCurrEstab_leaf),
			ARC(10, tcpInSegs_leaf),
			ARC(11, tcpOutSegs_leaf),
			ARC(12, tcpRetransSegs_leaf),
			ARC(13, tcpConnTable_node),
			ARC(14, tcpInErrs_leaf),
			ARC(15, tcpOutRsts_leaf),
			END_OF_ARC_LIST };
STATIC
MIBNODE_T	tcp_node = NODE("tcp", tcp_arcs);

extern int get_udp_uints();
STATIC
MIBLEAF_T	udpInDatagrams_leaf = LEAFM("udpInDatagrams", VT_COUNTER,
			RO, it_exists,
			get_udp_uints, null_set_proc, std_next,
			(char *)0,
			0x0000, 0x0C, 0x08);
STATIC
MIBLEAF_T	udpNoPorts_leaf = LEAFM("udpNoPorts", VT_COUNTER,
			RO, it_exists,
			get_udp_uints, null_set_proc, std_next,
			(char *)0,
			0x0000, 0x0C, 0x08);
STATIC
MIBLEAF_T	udpInErrors_leaf = LEAFM("udpInErrors", VT_COUNTER,
			RO, it_exists,
			get_udp_uints, null_set_proc, std_next,
			(char *)NULL,
			0x0000, 0x0C, 0x08);
STATIC
MIBLEAF_T	udpOutDatagrams_leaf = LEAFM("udpOutDatagrams", VT_COUNTER,
			RO, it_exists,
			get_udp_uints, null_set_proc, std_next,
			(char *)0,
			0x0000, 0x0C, 0x08);
extern int udptable_test();
extern int get_udptab_ipaddr();
extern int udptable_next();
STATIC
MIBLEAF_T	udpLocalAddress_leaf = LEAFM("udpLocalAddress", VT_IPADDRESS,
			RO, udptable_test,
			get_udptab_ipaddr, null_set_proc, udptable_next,
			(char *)NULL,
			0x0000, 0x0C, 0x08);
extern int get_udptab_localport();
STATIC
MIBLEAF_T	udpLocalPort_leaf = LEAFM("udpLocalPort", VT_NUMBER,
			RO, udptable_test,
			get_udptab_localport, null_set_proc, udptable_next,
			(char *)NULL,
			0x0000, 0x0C, 0x08);
STATIC
MIBARC_T	udpEntry_arcs[] = {
			ARC(1, udpLocalAddress_leaf),
			ARC(2, udpLocalPort_leaf),
			END_OF_ARC_LIST };
STATIC
MIBNODE_T	udpEntry_node = NODE("udpEntry", udpEntry_arcs);

STATIC
MIBARC_T	udpTable_arcs[] = {
			ARC(1, udpEntry_node),
			END_OF_ARC_LIST };
STATIC
MIBNODE_T	udpTable_node = NODE("udpTable", udpTable_arcs);

STATIC
MIBARC_T	udp_arcs[] = {
			ARC(1, udpInDatagrams_leaf),
			ARC(2, udpNoPorts_leaf),
			ARC(3, udpInErrors_leaf),
			ARC(4, udpOutDatagrams_leaf),
			ARC(5, udpTable_node),
			END_OF_ARC_LIST };
STATIC
MIBNODE_T	udp_node = NODE("udp", udp_arcs);

extern int get_ulong();
STATIC
MIBLEAF_T	snmpInPkts_leaf = LEAFM("snmpInPkts", VT_COUNTER,
			RO, it_exists,
			get_ulong, null_set_proc, std_next,
			(char *)&snmp_stats.snmpInPkts,
			0x0000, 0x0C, 0x08);
STATIC
MIBLEAF_T	snmpOutPkts_leaf = LEAFM("snmpOutPkts", VT_COUNTER,
			RO, it_exists,
			get_ulong, null_set_proc, std_next,
			(char *)&snmp_stats.snmpOutPkts,
			0x0000, 0x0C, 0x08);
STATIC
MIBLEAF_T	snmpInBadVersions_leaf = LEAFM("snmpInBadVersions", VT_COUNTER,
			RO, it_exists,
			get_ulong, null_set_proc, std_next,
			(char *)&snmp_stats.snmpInBadVersions,
			0x0000, 0x0C, 0x08);
STATIC
MIBLEAF_T	snmpInBadCommunityNames_leaf = LEAFM("snmpInBadCommunityNames", VT_COUNTER,
			RO, it_exists,
			get_ulong, null_set_proc, std_next,
			(char *)&snmp_stats.snmpInBadCommunityNames,
			0x0000, 0x0C, 0x08);
STATIC
MIBLEAF_T	snmpInBadCommunityUses_leaf = LEAFM("snmpInBadCommunityUses", VT_COUNTER,
			RO, it_exists,
			get_ulong, null_set_proc, std_next,
			(char *)&snmp_stats.snmpInBadCommunityUses,
			0x0000, 0x0C, 0x08);
STATIC
MIBLEAF_T	snmpInASNParseErrs_leaf = LEAFM("snmpInASNParseErrs", VT_COUNTER,
			RO, it_exists,
			get_ulong, null_set_proc, std_next,
			(char *)&snmp_stats.snmpInASNParseErrs,
			0x0000, 0x0C, 0x08);
STATIC
MIBLEAF_T	snmpInTooBigs_leaf = LEAFM("snmpInTooBigs", VT_COUNTER,
			RO, it_exists,
			get_ulong, null_set_proc, std_next,
			(char *)&snmp_stats.snmpInTooBigs,
			0x0000, 0x0C, 0x08);
STATIC
MIBLEAF_T	snmpInNoSuchNames_leaf = LEAFM("snmpInNoSuchNames", VT_COUNTER,
			RO, it_exists,
			get_ulong, null_set_proc, std_next,
			(char *)&snmp_stats.snmpInNoSuchNames,
			0x0000, 0x0C, 0x08);
STATIC
MIBLEAF_T	snmpInBadValues_leaf = LEAFM("snmpInBadValues", VT_COUNTER,
			RO, it_exists,
			get_ulong, null_set_proc, std_next,
			(char *)&snmp_stats.snmpInBadValues,
			0x0000, 0x0C, 0x08);
STATIC
MIBLEAF_T	snmpInReadOnlys_leaf = LEAFM("snmpInReadOnlys", VT_COUNTER,
			RO, it_exists,
			get_ulong, null_set_proc, std_next,
			(char *)&snmp_stats.snmpInReadOnlys,
			0x0000, 0x0C, 0x08);
STATIC
MIBLEAF_T	snmpInGenErrs_leaf = LEAFM("snmpInGenErrs", VT_COUNTER,
			RO, it_exists,
			get_ulong, null_set_proc, std_next,
			(char *)&snmp_stats.snmpInGenErrs,
			0x0000, 0x0C, 0x08);
STATIC
MIBLEAF_T	snmpInTotalReqVars_leaf = LEAFM("snmpInTotalReqVars", VT_COUNTER,
			RO, it_exists,
			get_ulong, null_set_proc, std_next,
			(char *)&snmp_stats.snmpInTotalReqVars,
			0x0000, 0x0C, 0x08);
STATIC
MIBLEAF_T	snmpInTotalSetVars_leaf = LEAFM("snmpInTotalSetVars", VT_COUNTER,
			RO, it_exists,
			get_ulong, null_set_proc, std_next,
			(char *)&snmp_stats.snmpInTotalSetVars,
			0x0000, 0x0C, 0x08);
STATIC
MIBLEAF_T	snmpInGetRequests_leaf = LEAFM("snmpInGetRequests", VT_COUNTER,
			RO, it_exists,
			get_ulong, null_set_proc, std_next,
			(char *)&snmp_stats.snmpInGetRequests,
			0x0000, 0x0C, 0x08);
STATIC
MIBLEAF_T	snmpInGetNexts_leaf = LEAFM("snmpInGetNexts", VT_COUNTER,
			RO, it_exists,
			get_ulong, null_set_proc, std_next,
			(char *)&snmp_stats.snmpInGetNexts,
			0x0000, 0x0C, 0x08);
STATIC
MIBLEAF_T	snmpInSetRequests_leaf = LEAFM("snmpInSetRequests", VT_COUNTER,
			RO, it_exists,
			get_ulong, null_set_proc, std_next,
			(char *)&snmp_stats.snmpInSetRequests,
			0x0000, 0x0C, 0x08);
STATIC
MIBLEAF_T	snmpInGetResponses_leaf = LEAFM("snmpInGetResponses", VT_COUNTER,
			RO, it_exists,
			get_ulong, null_set_proc, std_next,
			(char *)&snmp_stats.snmpInGetResponses,
			0x0000, 0x0C, 0x08);
STATIC
MIBLEAF_T	snmpInTraps_leaf = LEAFM("snmpInTraps", VT_COUNTER,
			RO, it_exists,
			get_ulong, null_set_proc, std_next,
			(char *)&snmp_stats.snmpInTraps,
			0x0000, 0x0C, 0x08);
STATIC
MIBLEAF_T	snmpOutTooBigs_leaf = LEAFM("snmpOutTooBigs", VT_COUNTER,
			RO, it_exists,
			get_ulong, null_set_proc, std_next,
			(char *)&snmp_stats.snmpOutTooBigs,
			0x0000, 0x0C, 0x08);
STATIC
MIBLEAF_T	snmpOutNoSuchNames_leaf = LEAFM("snmpOutNoSuchNames", VT_COUNTER,
			RO, it_exists,
			get_ulong, null_set_proc, std_next,
			(char *)&snmp_stats.snmpOutNoSuchNames,
			0x0000, 0x0C, 0x08);
STATIC
MIBLEAF_T	snmpOutBadValues_leaf = LEAFM("snmpOutBadValues", VT_COUNTER,
			RO, it_exists,
			get_ulong, null_set_proc, std_next,
			(char *)&snmp_stats.snmpOutBadValues,
			0x0000, 0x0C, 0x08);
STATIC
MIBLEAF_T	snmpOutGenErrs_leaf = LEAFM("snmpOutGenErrs", VT_COUNTER,
			RO, it_exists,
			get_ulong, null_set_proc, std_next,
			(char *)&snmp_stats.snmpOutGenErrs,
			0x0000, 0x0C, 0x08);
STATIC
MIBLEAF_T	snmpOutGetRequests_leaf = LEAFM("snmpOutGetRequests", VT_COUNTER,
			RO, it_exists,
			get_ulong, null_set_proc, std_next,
			(char *)&snmp_stats.snmpOutGetRequests,
			0x0000, 0x0C, 0x08);
STATIC
MIBLEAF_T	snmpOutGetNexts_leaf = LEAFM("snmpOutGetNexts", VT_COUNTER,
			RO, it_exists,
			get_ulong, null_set_proc, std_next,
			(char *)&snmp_stats.snmpOutGetNexts,
			0x0000, 0x0C, 0x08);
STATIC
MIBLEAF_T	snmpOutSetRequests_leaf = LEAFM("snmpOutSetRequests", VT_COUNTER,
			RO, it_exists,
			get_ulong, null_set_proc, std_next,
			(char *)&snmp_stats.snmpOutSetRequests,
			0x0000, 0x0C, 0x08);
STATIC
MIBLEAF_T	snmpOutGetResponses_leaf = LEAFM("snmpOutGetResponses", VT_COUNTER,
			RO, it_exists,
			get_ulong, null_set_proc, std_next,
			(char *)&snmp_stats.snmpOutGetResponses,
			0x0000, 0x0C, 0x08);
STATIC
MIBLEAF_T	snmpOutTraps_leaf = LEAFM("snmpOutTraps", VT_COUNTER,
			RO, it_exists,
			get_ulong, null_set_proc, std_next,
			(char *)&snmp_stats.snmpOutTraps,
			0x0000, 0x0C, 0x08);
extern int get_snmpEnableAuthTraps();
extern int set_snmpEnableAuthTraps();
STATIC
MIBLEAF_T	snmpEnableAuthenTraps_leaf = LEAFM("snmpEnableAuthenTraps", VT_NUMBER,
			RW, it_exists,
			get_snmpEnableAuthTraps, set_snmpEnableAuthTraps, std_next,
			(char *)0,
			0x0000, 0x0C, 0x08);
STATIC
MIBARC_T	snmp_arcs[] = {
			ARC(1, snmpInPkts_leaf),
			ARC(2, snmpOutPkts_leaf),
			ARC(3, snmpInBadVersions_leaf),
			ARC(4, snmpInBadCommunityNames_leaf),
			ARC(5, snmpInBadCommunityUses_leaf),
			ARC(6, snmpInASNParseErrs_leaf),
			ARC(8, snmpInTooBigs_leaf),
			ARC(9, snmpInNoSuchNames_leaf),
			ARC(10, snmpInBadValues_leaf),
			ARC(11, snmpInReadOnlys_leaf),
			ARC(12, snmpInGenErrs_leaf),
			ARC(13, snmpInTotalReqVars_leaf),
			ARC(14, snmpInTotalSetVars_leaf),
			ARC(15, snmpInGetRequests_leaf),
			ARC(16, snmpInGetNexts_leaf),
			ARC(17, snmpInSetRequests_leaf),
			ARC(18, snmpInGetResponses_leaf),
			ARC(19, snmpInTraps_leaf),
			ARC(20, snmpOutTooBigs_leaf),
			ARC(21, snmpOutNoSuchNames_leaf),
			ARC(22, snmpOutBadValues_leaf),
			ARC(24, snmpOutGenErrs_leaf),
			ARC(25, snmpOutGetRequests_leaf),
			ARC(26, snmpOutGetNexts_leaf),
			ARC(27, snmpOutSetRequests_leaf),
			ARC(28, snmpOutGetResponses_leaf),
			ARC(29, snmpOutTraps_leaf),
			ARC(30, snmpEnableAuthenTraps_leaf),
			END_OF_ARC_LIST };
STATIC
MIBNODE_T	snmp_node = NODE("snmp", snmp_arcs);

STATIC
MIBARC_T	mib_arcs[] = {
			ARC(1, system_node),
			ARC(2, interfaces_node),
			ARC(3, at_node),
			ARC(4, ip_node),
			ARC(5, icmp_node),
			ARC(6, tcp_node),
			ARC(7, udp_node),
			ARC(11, snmp_node),
			END_OF_ARC_LIST };
STATIC
MIBNODE_T	mib_node = NODE("mib", mib_arcs);

STATIC
MIBARC_T	mgmt_arcs[] = {
			ARC(1, mib_node),
			END_OF_ARC_LIST };
STATIC
MIBNODE_T	mgmt_node = NODE("mgmt", mgmt_arcs);

STATIC
MIBARC_T	products_arcs[] = {
			END_OF_ARC_LIST };
STATIC
MIBNODE_T	products_node = NODE("products", products_arcs);

STATIC
MIBLEAF_T	agentDescr_leaf = LEAFM("agentDescr", VT_STRING,
			RO, it_exists,
			get_string, null_set_proc, std_next,
			"Sun Microsystems SNMP Agent",
			0x0000, 0x0F, 0x0A);
extern int get_hostID();
STATIC
MIBLEAF_T	hostID_leaf = LEAFM("hostID", VT_STRING,
			RO, it_exists,
			get_hostID, null_set_proc, std_next,
			(char *)NULL,
			0x0000, 0x0F, 0x0A);
extern int get_motd();
STATIC
MIBLEAF_T	motd_leaf = LEAFM("motd", VT_STRING,
			RO, it_exists,
			get_motd, null_set_proc, std_next,
			(char *)NULL,
			0x0000, 0x0F, 0x0A);
extern int get_unixTime();
STATIC
MIBLEAF_T	unixTime_leaf = LEAFM("unixTime", VT_COUNTER,
			RO, it_exists,
			get_unixTime, null_set_proc, std_next,
			(char *)NULL,
			0x0000, 0x0F, 0x0A);
STATIC
MIBARC_T	sunSystem_arcs[] = {
			ARC(1, agentDescr_leaf),
			ARC(2, hostID_leaf),
			ARC(3, motd_leaf),
			ARC(4, unixTime_leaf),
			END_OF_ARC_LIST };
STATIC
MIBNODE_T	sunSystem_node = NODE("sunSystem", sunSystem_arcs);

STATIC
MIBARC_T	sunInterfaces_arcs[] = {
			END_OF_ARC_LIST };
STATIC
MIBNODE_T	sunInterfaces_node = NODE("sunInterfaces", sunInterfaces_arcs);

STATIC
MIBARC_T	sunAt_arcs[] = {
			END_OF_ARC_LIST };
STATIC
MIBNODE_T	sunAt_node = NODE("sunAt", sunAt_arcs);

STATIC
MIBARC_T	sunIp_arcs[] = {
			END_OF_ARC_LIST };
STATIC
MIBNODE_T	sunIp_node = NODE("sunIp", sunIp_arcs);

STATIC
MIBARC_T	sunIcmp_arcs[] = {
			END_OF_ARC_LIST };
STATIC
MIBNODE_T	sunIcmp_node = NODE("sunIcmp", sunIcmp_arcs);

STATIC
MIBARC_T	sunTcp_arcs[] = {
			END_OF_ARC_LIST };
STATIC
MIBNODE_T	sunTcp_node = NODE("sunTcp", sunTcp_arcs);

STATIC
MIBARC_T	sunUdp_arcs[] = {
			END_OF_ARC_LIST };
STATIC
MIBNODE_T	sunUdp_node = NODE("sunUdp", sunUdp_arcs);

STATIC
MIBARC_T	sunSnmp_arcs[] = {
			END_OF_ARC_LIST };
STATIC
MIBNODE_T	sunSnmp_node = NODE("sunSnmp", sunSnmp_arcs);

extern int pstable_test();
extern int get_psProcessID();
extern int pstable_next();
STATIC
MIBLEAF_T	psProcessID_leaf = LEAFM("psProcessID", VT_NUMBER,
			RO, pstable_test,
			get_psProcessID, null_set_proc, pstable_next,
			(char *)NULL,
			0x0000, 0x0C, 0x08);
extern int get_psParentProcessID();
STATIC
MIBLEAF_T	psParentProcessID_leaf = LEAFM("psParentProcessID", VT_NUMBER,
			RO, pstable_test,
			get_psParentProcessID, null_set_proc, pstable_next,
			(char *)NULL,
			0x0000, 0x0C, 0x08);
extern int get_psProcessSize();
STATIC
MIBLEAF_T	psProcessSize_leaf = LEAFM("psProcessSize", VT_NUMBER,
			RO, pstable_test,
			get_psProcessSize, null_set_proc, pstable_next,
			(char *)NULL,
			0x0000, 0x0C, 0x08);
extern int get_psProcessCpuTime();
STATIC
MIBLEAF_T	psProcessCpuTime_leaf = LEAFM("psProcessCpuTime", VT_NUMBER,
			RO, pstable_test,
			get_psProcessCpuTime, null_set_proc, pstable_next,
			(char *)NULL,
			0x0000, 0x0C, 0x08);
extern int get_psProcessState();
STATIC
MIBLEAF_T	psProcessState_leaf = LEAFM("psProcessState", VT_STRING,
			RO, pstable_test,
			get_psProcessState, null_set_proc, pstable_next,
			(char *)NULL,
			0x0000, 0x0C, 0x08);
extern int get_psProcessWaitChannel();
STATIC
MIBLEAF_T	psProcessWaitChannel_leaf = LEAFM("psProcessWaitChannel", VT_STRING,
			RO, pstable_test,
			get_psProcessWaitChannel, null_set_proc, pstable_next,
			(char *)NULL,
			0x0000, 0x0C, 0x08);
extern int get_psProcessTTY();
STATIC
MIBLEAF_T	psProcessTTY_leaf = LEAFM("psProcessTTY", VT_STRING,
			RO, pstable_test,
			get_psProcessTTY, null_set_proc, pstable_next,
			(char *)NULL,
			0x0000, 0x0C, 0x08);
extern int get_psProcessUserName();
STATIC
MIBLEAF_T	psProcessUserName_leaf = LEAFM("psProcessUserName", VT_STRING,
			RO, pstable_test,
			get_psProcessUserName, null_set_proc, pstable_next,
			(char *)NULL,
			0x0000, 0x0C, 0x08);
extern int get_psProcessUserID();
STATIC
MIBLEAF_T	psProcessUserID_leaf = LEAFM("psProcessUserID", VT_NUMBER,
			RO, pstable_test,
			get_psProcessUserID, null_set_proc, pstable_next,
			(char *)NULL,
			0x0000, 0x0C, 0x08);
extern int get_psProcessName();
STATIC
MIBLEAF_T	psProcessName_leaf = LEAFM("psProcessName", VT_STRING,
			RO, pstable_test,
			get_psProcessName, null_set_proc, pstable_next,
			(char *)NULL,
			0x0000, 0x0C, 0x08);
extern int set_psProcessStatus();
STATIC
MIBLEAF_T	psProcessStatus_leaf = LEAFM("psProcessStatus", VT_NUMBER,
			RW, pstable_test,
			get_cookie, set_psProcessStatus, pstable_next,
			(char *)0,
			0x0000, 0x0C, 0x08);
STATIC
MIBARC_T	psEntry_arcs[] = {
			ARC(1, psProcessID_leaf),
			ARC(2, psParentProcessID_leaf),
			ARC(3, psProcessSize_leaf),
			ARC(4, psProcessCpuTime_leaf),
			ARC(5, psProcessState_leaf),
			ARC(6, psProcessWaitChannel_leaf),
			ARC(7, psProcessTTY_leaf),
			ARC(8, psProcessUserName_leaf),
			ARC(9, psProcessUserID_leaf),
			ARC(10, psProcessName_leaf),
			ARC(11, psProcessStatus_leaf),
			END_OF_ARC_LIST };
STATIC
MIBNODE_T	psEntry_node = NODE("psEntry", psEntry_arcs);

STATIC
MIBARC_T	sunProcessTable_arcs[] = {
			ARC(1, psEntry_node),
			END_OF_ARC_LIST };
STATIC
MIBNODE_T	sunProcessTable_node = NODE("sunProcessTable", sunProcessTable_arcs);

STATIC
MIBARC_T	sunProcesses_arcs[] = {
			ARC(1, sunProcessTable_node),
			END_OF_ARC_LIST };
STATIC
MIBNODE_T	sunProcesses_node = NODE("sunProcesses", sunProcesses_arcs);

extern int get_rsCpuTime1();
STATIC
MIBLEAF_T	rsCpuTime1_leaf = LEAFM("rsCpuTime1", VT_COUNTER,
			RO, it_exists,
			get_rsCpuTime1, null_set_proc, std_next,
			(char *)NULL,
			0x0000, 0x0C, 0x08);
extern int get_rsCpuTime2();
STATIC
MIBLEAF_T	rsCpuTime2_leaf = LEAFM("rsCpuTime2", VT_COUNTER,
			RO, it_exists,
			get_rsCpuTime2, null_set_proc, std_next,
			(char *)NULL,
			0x0000, 0x0C, 0x08);
extern int get_rsCpuTime3();
STATIC
MIBLEAF_T	rsCpuTime3_leaf = LEAFM("rsCpuTime3", VT_COUNTER,
			RO, it_exists,
			get_rsCpuTime3, null_set_proc, std_next,
			(char *)NULL,
			0x0000, 0x0C, 0x08);
extern int get_rsCpuTime4();
STATIC
MIBLEAF_T	rsCpuTime4_leaf = LEAFM("rsCpuTime4", VT_COUNTER,
			RO, it_exists,
			get_rsCpuTime4, null_set_proc, std_next,
			(char *)NULL,
			0x0000, 0x0C, 0x08);
extern int get_rsDiskXfer1();
STATIC
MIBLEAF_T	rsDiskXfer1_leaf = LEAFM("rsDiskXfer1", VT_COUNTER,
			RO, it_exists,
			get_rsDiskXfer1, null_set_proc, std_next,
			(char *)NULL,
			0x0000, 0x0C, 0x08);
extern int get_rsDiskXfer2();
STATIC
MIBLEAF_T	rsDiskXfer2_leaf = LEAFM("rsDiskXfer2", VT_COUNTER,
			RO, it_exists,
			get_rsDiskXfer2, null_set_proc, std_next,
			(char *)NULL,
			0x0000, 0x0C, 0x08);
extern int get_rsDiskXfer3();
STATIC
MIBLEAF_T	rsDiskXfer3_leaf = LEAFM("rsDiskXfer3", VT_COUNTER,
			RO, it_exists,
			get_rsDiskXfer3, null_set_proc, std_next,
			(char *)NULL,
			0x0000, 0x0C, 0x08);
extern int get_rsDiskXfer4();
STATIC
MIBLEAF_T	rsDiskXfer4_leaf = LEAFM("rsDiskXfer4", VT_COUNTER,
			RO, it_exists,
			get_rsDiskXfer4, null_set_proc, std_next,
			(char *)NULL,
			0x0000, 0x0C, 0x08);
extern int get_rsVPagesIn();
STATIC
MIBLEAF_T	rsVPagesIn_leaf = LEAFM("rsVPagesIn", VT_COUNTER,
			RO, it_exists,
			get_rsVPagesIn, null_set_proc, std_next,
			(char *)NULL,
			0x0000, 0x0C, 0x08);
extern int get_rsVPagesOut();
STATIC
MIBLEAF_T	rsVPagesOut_leaf = LEAFM("rsVPagesOut", VT_COUNTER,
			RO, it_exists,
			get_rsVPagesOut, null_set_proc, std_next,
			(char *)NULL,
			0x0000, 0x0C, 0x08);
extern int get_rsVSwapIn();
STATIC
MIBLEAF_T	rsVSwapIn_leaf = LEAFM("rsVSwapIn", VT_COUNTER,
			RO, it_exists,
			get_rsVSwapIn, null_set_proc, std_next,
			(char *)NULL,
			0x0000, 0x0C, 0x08);
extern int get_rsVSwapOut();
STATIC
MIBLEAF_T	rsVSwapOut_leaf = LEAFM("rsVSwapOut", VT_COUNTER,
			RO, it_exists,
			get_rsVSwapOut, null_set_proc, std_next,
			(char *)NULL,
			0x0000, 0x0C, 0x08);
extern int get_rsVIntr();
STATIC
MIBLEAF_T	rsVIntr_leaf = LEAFM("rsVIntr", VT_COUNTER,
			RO, it_exists,
			get_rsVIntr, null_set_proc, std_next,
			(char *)NULL,
			0x0000, 0x0C, 0x08);
extern int get_rsIfInPackets();
STATIC
MIBLEAF_T	rsIfInPackets_leaf = LEAFM("rsIfInPackets", VT_COUNTER,
			RO, it_exists,
			get_rsIfInPackets, null_set_proc, std_next,
			(char *)NULL,
			0x0000, 0x0C, 0x08);
extern int get_rsIfOutPackets();
STATIC
MIBLEAF_T	rsIfOutPackets_leaf = LEAFM("rsIfOutPackets", VT_COUNTER,
			RO, it_exists,
			get_rsIfOutPackets, null_set_proc, std_next,
			(char *)NULL,
			0x0000, 0x0C, 0x08);
extern int get_rsIfInErrors();
STATIC
MIBLEAF_T	rsIfInErrors_leaf = LEAFM("rsIfInErrors", VT_COUNTER,
			RO, it_exists,
			get_rsIfInErrors, null_set_proc, std_next,
			(char *)NULL,
			0x0000, 0x0C, 0x08);
extern int get_rsIfOutErrors();
STATIC
MIBLEAF_T	rsIfOutErrors_leaf = LEAFM("rsIfOutErrors", VT_COUNTER,
			RO, it_exists,
			get_rsIfOutErrors, null_set_proc, std_next,
			(char *)NULL,
			0x0000, 0x0C, 0x08);
extern int get_rsIfCollisions();
STATIC
MIBLEAF_T	rsIfCollisions_leaf = LEAFM("rsIfCollisions", VT_COUNTER,
			RO, it_exists,
			get_rsIfCollisions, null_set_proc, std_next,
			(char *)NULL,
			0x0000, 0x0C, 0x08);
STATIC
MIBARC_T	sunHostPerf_arcs[] = {
			ARC(1, rsCpuTime1_leaf),
			ARC(2, rsCpuTime2_leaf),
			ARC(3, rsCpuTime3_leaf),
			ARC(4, rsCpuTime4_leaf),
			ARC(5, rsDiskXfer1_leaf),
			ARC(6, rsDiskXfer2_leaf),
			ARC(7, rsDiskXfer3_leaf),
			ARC(8, rsDiskXfer4_leaf),
			ARC(9, rsVPagesIn_leaf),
			ARC(10, rsVPagesOut_leaf),
			ARC(11, rsVSwapIn_leaf),
			ARC(12, rsVSwapOut_leaf),
			ARC(13, rsVIntr_leaf),
			ARC(14, rsIfInPackets_leaf),
			ARC(15, rsIfOutPackets_leaf),
			ARC(16, rsIfInErrors_leaf),
			ARC(17, rsIfOutErrors_leaf),
			ARC(18, rsIfCollisions_leaf),
			END_OF_ARC_LIST };
STATIC
MIBNODE_T	sunHostPerf_node = NODE("sunHostPerf", sunHostPerf_arcs);

STATIC
MIBARC_T	sunMib_arcs[] = {
			ARC(1, sunSystem_node),
			ARC(2, sunInterfaces_node),
			ARC(3, sunAt_node),
			ARC(4, sunIp_node),
			ARC(5, sunIcmp_node),
			ARC(6, sunTcp_node),
			ARC(7, sunUdp_node),
			ARC(11, sunSnmp_node),
			ARC(12, sunProcesses_node),
			ARC(13, sunHostPerf_node),
			END_OF_ARC_LIST };
STATIC
MIBNODE_T	sunMib_node = NODE("sunMib", sunMib_arcs);

STATIC
MIBARC_T	sun_arcs[] = {
			ARC(2, products_node),
			ARC(3, sunMib_node),
			END_OF_ARC_LIST };
STATIC
MIBNODE_T	sun_node = NODE("sun", sun_arcs);

STATIC
MIBARC_T	enterprises_arcs[] = {
			ARC(42, sun_node),
			END_OF_ARC_LIST };
STATIC
MIBNODE_T	enterprises_node = NODE("enterprises", enterprises_arcs);

STATIC
MIBARC_T	private_arcs[] = {
			ARC(1, enterprises_node),
			END_OF_ARC_LIST };
STATIC
MIBNODE_T	private_node = NODE("private", private_arcs);

STATIC
MIBARC_T	internet_arcs[] = {
			ARC(2, mgmt_node),
			ARC(4, private_node),
			END_OF_ARC_LIST };
STATIC
MIBNODE_T	internet_node = NODE("internet", internet_arcs);

STATIC
MIBARC_T	dod_arcs[] = {
			ARC(1, internet_node),
			END_OF_ARC_LIST };
STATIC
MIBNODE_T	dod_node = NODE("dod", dod_arcs);

STATIC
MIBARC_T	org_arcs[] = {
			ARC(6, dod_node),
			END_OF_ARC_LIST };
STATIC
MIBNODE_T	org_node = NODE("org", org_arcs);

STATIC
MIBARC_T	iso_arcs[] = {
			ARC(3, org_node),
			END_OF_ARC_LIST };
STATIC
MIBNODE_T	iso_node = NODE("iso", iso_arcs);

STATIC
MIBARC_T	mib_root_arcs[] = {
			ARC(1, iso_node),
			END_OF_ARC_LIST };
MIBNODE_T	mib_root_node = NODE("mib_root", mib_root_arcs);

