#
#ident	"@(#)Makefile	1.6	97/05/23 SMI"
#
# Copyright (c) 1996 by Sun Microsystems, Inc.
#
# sgs/libelf/i386/Makefile


include		../Makefile.com

.KEEP_STATE:

include		../Makefile.targ

DYNFLAGS +=	-M ./mapfile-dem
