/*
 * Copyright (c) 1998 by Sun Microsystems, Inc.
 * All rights reserved.
 */

#pragma ident	"@(#)pr_waitid.c	1.1	98/01/29 SMI"

#include <sys/isa_defs.h>

#ifdef _LP64
#define	_SYSCALL32
#endif

#include <stdlib.h>
#include <unistd.h>
#include <string.h>
#include <errno.h>
#include <sys/types.h>
#include <sys/wait.h>
#include "libproc.h"

#ifdef _LP64
static void
siginfo_32_to_n(const siginfo32_t *src, siginfo_t *dest)
{
	(void) memset(dest, 0, sizeof (*dest));

	/*
	 * The absolute minimum content is si_signo and si_code.
	 */
	dest->si_signo = src->si_signo;
	if ((dest->si_code = src->si_code) == SI_NOINFO)
		return;

	/*
	 * A siginfo generated by user level is structured
	 * differently from one generated by the kernel.
	 */
	if (SI_FROMUSER(src)) {
		dest->si_pid = src->si_pid;
		dest->si_uid = src->si_uid;
		if (SI_CANQUEUE(src->si_code))
			dest->si_value.sival_int =
				(long)(uint32_t)src->si_value.sival_int;
		return;
	}

	dest->si_errno = src->si_errno;

	switch (src->si_signo) {
	default:
		dest->si_pid = src->si_pid;
		dest->si_uid = src->si_uid;
		dest->si_value.sival_int =
			(long)(uint32_t)src->si_value.sival_int;
		break;
	case SIGCLD:
		dest->si_pid = src->si_pid;
		dest->si_status = src->si_status;
		dest->si_stime = src->si_stime;
		dest->si_utime = src->si_utime;
		break;
	case SIGSEGV:
	case SIGBUS:
	case SIGILL:
	case SIGTRAP:
	case SIGFPE:
	case SIGEMT:
		dest->si_addr = (void *)(caddr32_t)src->si_addr;
		dest->si_trapno = src->si_trapno;
		dest->si_pc = (void *)(caddr32_t)src->si_pc;
		break;
	case SIGPOLL:
	case SIGXFSZ:
		dest->si_fd = src->si_fd;
		dest->si_band = src->si_band;
		break;
	case SIGPROF:
		dest->si_faddr = (void *)(caddr32_t)src->si_faddr;
		dest->si_tstamp.tv_sec = src->si_tstamp.tv_sec;
		dest->si_tstamp.tv_nsec = src->si_tstamp.tv_nsec;
		dest->si_syscall = src->si_syscall;
		dest->si_nsysarg = src->si_nsysarg;
		dest->si_fault = src->si_fault;
		break;
	}
}
#endif	/* _LP64 */

/*
 * waitid() system call -- executed by subject process
 */
int
pr_waitid(struct ps_prochandle *Pr,
	idtype_t idtype, id_t id, siginfo_t *infop, int options)
{
	sysret_t rval;			/* return value from waitid() */
	argdes_t argd[4];		/* arg descriptors for waitid() */
	argdes_t *adp;
#ifdef _LP64
	siginfo32_t siginfo32;
#endif	/* _LP64 */

	if (Pr == NULL)		/* no subject process */
		return (waitid(idtype, id, infop, options));

	adp = &argd[0];		/* idtype argument */
	adp->arg_value = idtype;
	adp->arg_object = NULL;
	adp->arg_type = AT_BYVAL;
	adp->arg_inout = AI_INPUT;
	adp->arg_size = 0;

	adp++;			/* id argument */
	adp->arg_value = id;
	adp->arg_object = NULL;
	adp->arg_type = AT_BYVAL;
	adp->arg_inout = AI_INPUT;
	adp->arg_size = 0;

	adp++;			/* infop argument */
	adp->arg_value = 0;
	adp->arg_type = AT_BYREF;
	adp->arg_inout = AI_OUTPUT;
#ifdef _LP64
	if (Pstatus(Pr)->pr_dmodel == PR_MODEL_ILP32) {
		adp->arg_object = &siginfo32;
		adp->arg_size = sizeof (siginfo32);
	} else {
		adp->arg_object = infop;
		adp->arg_size = sizeof (*infop);
	}
#else	/* _LP64 */
	adp->arg_object = infop;
	adp->arg_size = sizeof (*infop);
#endif	/* _LP64 */

	adp++;			/* options argument */
	adp->arg_value = options;
	adp->arg_object = NULL;
	adp->arg_type = AT_BYVAL;
	adp->arg_inout = AI_INPUT;
	adp->arg_size = 0;

	rval = Psyscall(Pr, SYS_waitsys, 4, &argd[0]);

	if (rval.sys_errno < 0)
		rval.sys_errno = ENOSYS;

	if (rval.sys_errno) {
		errno = rval.sys_errno;
		return (-1);
	}

#ifdef _LP64
	if (Pstatus(Pr)->pr_dmodel == PR_MODEL_ILP32)
		siginfo_32_to_n(&siginfo32, infop);
#endif	/* _LP64 */
	return (0);
}
