#
#ident	"@(#)Makefile.targ.64	1.7	98/01/05 SMI"
#
# Copyright (c) 1997, by Sun Microsystems, Inc.
# All rights reserved.
#
# cmd/sgs/libelf/Makefile.targ.64

LIBS =		$(DYNLIB) $(LINTLIB)

objs/%.o \
profs/%.o \
pics/%.o:	%.c
		$(COMPILE.c) -o $@ $<
		$(POST_PROCESS_O)

objs/%64.o \
profs/%64.o \
pics/%64.o:	../common/%.c
		$(COMPILE.c) -D_ELF64 -o $@ $<
		$(POST_PROCESS_O)

objs/%.o \
profs/%.o \
pics/%.o:	../misc/%.c
		$(COMPILE.c) -DELF -o $@ $<
		$(POST_PROCESS_O)

objs/%.o \
profs/%.o \
pics/%.o:	../common/%.c
		$(COMPILE.c) -o $@ $<
		$(POST_PROCESS_O)

all:		$(BLTSRCS) .WAIT $(LIBS) $(LIBLINKS)

install:	all .WAIT $(ROOTLIBS64) $(ROOTLINKS64)

lint:		$(LINTLIB)

$(LINTLIB):	$(XLINTOUT)

$(XLINTOUT):	$(LIBSRCS)
		$(LINT.c) $(LIBSRCS) $(LDLIBS) > $(XLINTOUT) 2>&1

delete:
		$(RM) $(DYNLIB)

$(DYNLIB):	$(MAPFILE)

$(LIBLINKS):
	$(RM) $(LIBLINKS)
	$(SYMLINK) $(DYNLIB) $(LIBLINKS)

# include common library targets
#
include		$(SRC)/lib/Makefile.targ

xlate.c:	../common/xlate.m4
		$(M4) < ../common/xlate.m4 > xlate.c

xlate64.c:	../common/xlate64.m4
		$(M4) < ../common/xlate64.m4 > xlate64.c

objs/msg.o \
pics/msg.o \
profs/msg.o:	msg.c

objs/error.o \
pics/error.o \
profs/error.o:	msg.h

objs/ar.o \
pics/ar.o \
profs/ar.o:	msg.h

objs/xlate.o \
pics/xlate.o \
profs/xlate.o:	xlate.c


# Derived source and header files (messaging).  Make sure that the sgsmsg
# command is constructed - libelf might not be built with the whole sgs.

catalog:	$(BLTMESG)

# Tell chmsg.csh that we want a 64-bit architecture.

SGSMSGCHKFLAGS =	-64


$(BLTDEFS) + \
$(BLTDATA) + \
$(BLTMESG) :    $(SGSTOOLS)/sgsmsg ../common/libelf.msg xlate.c xlate64.c
		$(SGSTOOLS)/sgsmsg $(SGSMSGFLAGS) ../common/libelf.msg
		@ csh $(SGSTOOLS)/../chkmsg.csh $(SGSMSGCHKFLAGS) \
			../common/libelf.msg $(LIBSRCS)

$(SGSTOOLS)/sgsmsg: FRC
		@ cd $(SGSTOOLS); pwd; $(MAKE) catalog
		@ pwd

#
# 64-bit overrides
#
include ../../Makefile.sub.64

FRC:
