#
# Copyright (c) 1997, by Sun Microsystems, Inc.
# All rights reserved.
#
#pragma ident	"@(#)Makefile 1.1	97/09/25 SMI"
#
# lib/libplot/vt0/i386/Makefile

include ../Makefile.com

all: $(LIBS)

.KEEP_STATE:

install: all $(ROOTLIBS) $(ROOTLINKS) $(ROOTLINT)
