#
# Copyright (c) 1997 by Sun Microsystems, Inc.
# All rights reserved.
#
#ident	"@(#)Makefile	1.1	97/12/01 SMI"
#
# lib/watchmalloc/i386/Makefile

include ../Makefile.com

.KEEP_STATE:

install: all $(ROOTLIBS)
