#!/bin/sh
#
#ident	"@(#)i.nametomajor_i386	1.9	98/01/26 SMI"
#
# Copyright (c) 1993-1995 by Sun Microsystems, Inc.
# All rights reserved.
#

PATH="/usr/bin:/usr/sbin:${PATH}"
export PATH

trap "rm -f /tmp/$$.*;exit" 0 1 2 3 13 15
TMP=/tmp/$$

os_rev=`uname -r`

if [ -f ${BASEDIR}/etc/rem_name_to_major ]; then
	rem_file="${BASEDIR}/etc/rem_name_to_major"
fi

# adds new major numbers to system for device drivers
# Usage:
#	add_major name1 name2 name3 name4 ....

add_major()
{
sort +1 -2n ${dest} ${rem_file}| nawk '#
BEGIN	{oldmajor = -1}
NR == 1	{n=split(namelist,x)
	 if (n < 1)
	    exit(1)
	 for (i=1; i<=n; i++)
	    chklist[x[i]]++
	}
	{for (name in chklist)
	 {
	    if ($1 == name)
		delete chklist[name]
	 }
	 if (($2 - oldmajor) > 1)
	 {
	    gap++
	    gaplist[gap] = oldmajor " " $2;
	 }
	 oldmajor = $2;
	}
END	{addsize=1
	 for (name in chklist)
	    addlist[addsize++] = name
	
	 addidx = 1
	 for (i=1; i<=gap && addidx < addsize; i++)
	 {
	    split(gaplist[i],x)
	    begmajor = x[1]
	    endmajor = x[2]
	    for (begmajor++;begmajor < endmajor && addidx < addsize;)
	    {
		printf "%s %d\n",addlist[addidx],begmajor
		addidx++
		begmajor++
	    }
	 }
	 for (; addidx < addsize; addidx++)
	 {
	    oldmajor++
	    printf "%s %d\n",addlist[addidx],oldmajor
	 }
	}
' namelist="$*" - > $TMP.new
if [ -s $TMP.new ]
then
    echo "Adding following devices to ${dest}"
    cat $TMP.new
    sort +1 -2n ${dest} $TMP.new -o ${dest}
fi
}

while read src dest
do
	if [ ! -f $dest ] ; then
		cp $src $dest
	else
		sed -e '/^rip 4/d' \
		    -e '/^svloop 6/d' \
		    -e '/^tcl 7/d' \
		    -e '/^tco 8/d' \
		    -e '/^tcoo 9/d' \
		    -e '/^sp 10/d' \
		    -e '/^app 43/d' \
		    -e '/^tiqmouse 45/d' \
		    -e '/^svarp 51/d' \
		    -e '/^svip 52/d' \
		    -e '/^svrip 53/d' \
		    -e '/^svicmp 54/d' \
		    -e '/^svudp 55/d' \
		    -e '/^cmtp 103/d' \
		    -e '/^svtcp 56/d' \
		    -e 's/^tl 99/tl 105/' \
		    -e 's/^smc 105/smc 103/' $dest | sort +1 -2n > /tmp/tmp.$$
		cp /tmp/tmp.$$ $dest
		rm -f /tmp/tmp.$$
		cat $src |
	       (while read name major
		do
			if grep -w $name $dest > /dev/null 2>&1 ; then
				continue
			else
			case $os_rev in
			     "5.3") add_major $name;;
                             "5.4") add_major $name;; 
                             "5.5") add_major $name;; 
                           "5.5.1") add_major $name;; 
                               *) add_drv -b $BASEDIR  $name >/dev/null 2>&-
				     if  [ $? -eq 0 ] ; then
				         echo "Adding ${name} to ${dest}"
				     fi
				     ;;
			esac
			fi
		done)
    	sort +1 -2n ${dest} -o ${dest}
	fi
done
exit 0
