#!/bin/sh
#
#ident  "@(#)i.nametomajor_sparc 1.14 98/01/26 SMI"
#
# Copyright (c) 1993-1998 by Sun Microsystems, Inc.
# All rights reserved.
#


PATH="/usr/bin:/usr/sbin:${PATH}"
export PATH

trap "rm -f /tmp/$$.*;exit" 0 1 2 3 13 15
TMP=/tmp/$$

os_rev=`uname -r`

if [ -f ${BASEDIR}/etc/rem_name_to_major ]; then
	rem_file="${BASEDIR}/etc/rem_name_to_major"
fi

# adds new major numbers to system for device drivers
# Usage:
#	add_major name1 name2 name3 name4 ....

add_major()
{
sort +1 -2n ${dest} ${rem_file}| nawk '#
BEGIN	{oldmajor = -1}
NR == 1	{n=split(namelist,x)
	 if (n < 1)
	    exit(1)
	 for (i=1; i<=n; i++)
	    chklist[x[i]]++
	}
	{for (name in chklist)
	 {
	    if ($1 == name)
		delete chklist[name]
	 }
	 if (($2 - oldmajor) > 1)
	 {
	    gap++
	    gaplist[gap] = oldmajor " " $2;
	 }
	 oldmajor = $2;
	}
END	{addsize=1
	 for (name in chklist)
	    addlist[addsize++] = name
	
	 addidx = 1
	 for (i=1; i<=gap && addidx < addsize; i++)
	 {
	    split(gaplist[i],x)
	    begmajor = x[1]
	    endmajor = x[2]
	    for (begmajor++;begmajor < endmajor && addidx < addsize;)
	    {
		printf "%s %d\n",addlist[addidx],begmajor
		addidx++
		begmajor++
	    }
	 }
	 for (; addidx < addsize; addidx++)
	 {
	    oldmajor++
	    printf "%s %d\n",addlist[addidx],oldmajor
	 }
	}
' namelist="$*" - > $TMP.new
if [ -s $TMP.new ]
then
    echo "Adding following devices to ${dest}"
    cat $TMP.new
    sort +1 -2n ${dest} $TMP.new -o ${dest}
fi
}

while read src dest
do
	if [ ! -f $dest ] ; then
		cp $src $dest
	else
		sed -e '/^rip 4/d' \
		    -e '/^svloop 6/d' \
		    -e '/^tcl 7/d' \
		    -e '/^tco 8/d' \
		    -e '/^tcoo 9/d' \
		    -e '/^sp 10/d' \
		    -e '/^consfb 18/d' \
		    -e '/^XXunusedXX 18/d' \
		    -e '/^sw 20/d' \
		    -e '/^cgtwo 31/d' \
		    -e '/^xy 34/d' \
		    -e '/^xd 35/d' \
		    -e '/^pc 37/d' \
		    -e '/^app 43/d' \
		    -e '/^evq 45/d' \
		    -e '/^win 50/d' \
		    -e '/^svarp 51/d' \
		    -e '/^svip 52/d' \
		    -e '/^svrip 53/d' \
		    -e '/^svicmp 54/d' \
		    -e '/^svudp 55/d' \
		    -e '/^svtcp 56/d' \
		    -e '/^vme 60/d' \
		    -e '/^ie 63/d' \
		    -e '/^ncr 64/d' \
		    -e '/^xt 65/d' \
		    -e '/^id 66/d' \
		    -e '/^vmemem 67/d' \
		    -e '/^pn 75/d' \
		    -e '/^kmac 79/d' \
		    -e '/^ipi3sc 82/d' \
		    -e '/^cgfour 86/d' \
		    -e '/^cgeight-p4 87/d' \
		    -e '/^xdc 88/d' \
		    -e '/^xyc 89/d' \
		    -e '/^mcp 95/d' \
		    -e '/^mcpzsa 96/d' \
		    -e '/^mcpp 97/d' \
		    $dest > /tmp/tmp.$$
		cp /tmp/tmp.$$ $dest
		rm -f /tmp/tmp.$$
		cat $src |
	       (while read name major
		do
			if grep -w $name $dest > /dev/null 2>&1 ; then
				continue
			else
			case $os_rev in
			     "5.3") add_major $name;;
                             "5.4") add_major $name;; 
                             "5.5") add_major $name;; 
                           "5.5.1") add_major $name;; 
                               *) add_drv -b $BASEDIR  $name >/dev/null 2>&-
				     if  [ $? -eq 0 ] ; then
				         echo "Adding ${name} to ${dest}"
				     fi
				     ;;
			esac
			fi
		done)
    	sort +1 -2n ${dest} -o ${dest}
	fi
done
exit 0
