#
# Copyright (c) 1996-1997, by Sun Microsystems, Inc.
# All rights reserved.
#
#pragma ident   "@(#)Makefile 1.2     97/11/09 SMI"
#
# lib/libdevice/i386/Makefile

include ../Makefile.com

DYNFLAGS += $(DYNFLAGS32)

all: $(LIBS)

.KEEP_STATE:

install: all $(ROOTLIBS) $(ROOTLINKS) $(ROOTLINT)
