#
#ident	"@(#)Makefile	1.2	98/02/06 SMI"
#
# Copyright (c) 1996, by Sun Microsystems, Inc.
# All rights reserved.

include ../Makefile.com

.KEEP_STATE:

DATAFILES += 

all: $(FILES) $(MACHDATAFILES)
install: all pkg

include ../Makefile.targ
