#
# Copyright (c) 1996-1997, by Sun Microsystems, Inc.
# All rights reserved.
#
#ident	"@(#)Makefile 1.2	97/08/28 SMI"
#
# lib/libdevinfo/i386/Makefile

include ../Makefile.com

DYNFLAGS += $(DYNFLAGS32)

all: $(LIBS)

.KEEP_STATE:

install: all $(ROOTLIBS) $(ROOTLINKS)
