#
# Copyright (c) 1997, by Sun Microsystems, Inc.
# All rights reserved.
#
#ident	"@(#)Makefile	1.3	98/02/06 SMI"
#
# lib/libcurses/sparc/Makefile

include ../Makefile.com

DYNFLAGS += $(DYNFLAGS32)

.KEEP_STATE:

all: $(LIBS)

install: all $(STATICLIB) $(ROOTLIBS) $(ROOTLINKS) $(ROOTLINT)
