#
#ident	"@(#)Makefile	1.5	98/02/08 SMI"
#
# Copyright (c) 1997-1998 by Sun Microsystems, Inc.
# All rights reserved.
#
# uts/adb/i386/Makefile
#

ADB_BASE_DIR	= ..
ISADIR		= .
COMMONDIR	= $(ADB_BASE_DIR)/common
SYSDIR		= $(ADB_BASE_DIR)/..

SRCS += systemdump.dbg

include	$(COMMONDIR)/Makefile.com
