#
#ident	"@(#)Makefile	1.3	97/08/28 SMI"
#
# Copyright (c) 1997 by Sun Microsystems, Inc.
#
# lib/libcmd/i386/Makefile
#

include ../Makefile.com

DYNFLAGS += $(DYNFLAGS32)

.KEEP_STATE:

all: $(TXTS) $(LIBS)

install: all $(ROOTLIBS) $(ROOTLINKS) $(ROOTLINT)
