#
#pragma ident	"@(#)Makefile	1.3	97/08/31 SMI"
#
# Copyright (c) 1997 by Sun Microsystems, Inc.
#
# lib/libadm/sparcv9/Makefile
#

include ../Makefile.com
include ../../Makefile.lib.64

LIBS = $(DYNLIB) $(LINTLIB)

.KEEP_STATE:

all:	$(LIBS) $(TXTS)

install: all $(ROOTLIBS64) $(ROOTLINKS64)
